ACTORS = {'alienplanet0': {'DIM': (1152, 96),
                  'POS': (0, 576),
                  'name': 'alienplanet0',
                  'offsetkey': 'alienplanet',
                  'scripts': 'alienplanet',
                  'sprites': 'alienplanet',
                  'tangible': True},
 'alienplanet1': {'DIM': (0, 0),
                  'POS': (736, 832),
                  'name': 'alienplanet1',
                  'offsetkey': 'alienplanet',
                  'scripts': 'alienplanet',
                  'sprites': 'alienplanet',
                  'tangible': True},
 'beedleship0': {'DIM': (48, 48),
                 'POS': (320, 80),
                 'name': 'beedleship0',
                 'offsetkey': 'beedleship',
                 'scripts': 'beedleship',
                 'sprites': 'beedleship',
                 'tangible': False},
 'beedleshipspawner0': {'DIM': (48, 48),
                        'POS': (352, 64),
                        'name': 'beedleshipspawner0',
                        'offsetkey': 'beedleshipspawner',
                        'scripts': 'beedleshipspawner',
                        'sprites': 'beedleshipspawner',
                        'tangible': False},
 'beedleshipspawner1': {'DIM': (48, 48),
                        'POS': (816, 64),
                        'name': 'beedleshipspawner1',
                        'offsetkey': 'beedleshipspawner',
                        'scripts': 'beedleshipspawner',
                        'sprites': 'beedleshipspawner',
                        'tangible': False},
 'beedleshipspawner2': {'DIM': (48, 48),
                        'POS': (352, 128),
                        'name': 'beedleshipspawner2',
                        'offsetkey': 'beedleshipspawner',
                        'scripts': 'beedleshipspawner',
                        'sprites': 'beedleshipspawner',
                        'tangible': False},
 'beedleshipspawner3': {'DIM': (48, 48),
                        'POS': (816, 128),
                        'name': 'beedleshipspawner3',
                        'offsetkey': 'beedleshipspawner',
                        'scripts': 'beedleshipspawner',
                        'sprites': 'beedleshipspawner',
                        'tangible': False},
 'beedleshipspawner4': {'DIM': (48, 48),
                        'POS': (352, 192),
                        'name': 'beedleshipspawner4',
                        'offsetkey': 'beedleshipspawner',
                        'scripts': 'beedleshipspawner',
                        'sprites': 'beedleshipspawner',
                        'tangible': False},
 'beedleshipspawner5': {'DIM': (48, 48),
                        'POS': (816, 192),
                        'name': 'beedleshipspawner5',
                        'offsetkey': 'beedleshipspawner',
                        'scripts': 'beedleshipspawner',
                        'sprites': 'beedleshipspawner',
                        'tangible': False},
 'beedleshipspawner6': {'DIM': (48, 48),
                        'POS': (352, 256),
                        'name': 'beedleshipspawner6',
                        'offsetkey': 'beedleshipspawner',
                        'scripts': 'beedleshipspawner',
                        'sprites': 'beedleshipspawner',
                        'tangible': False},
 'beedleshipspawner7': {'DIM': (48, 48),
                        'POS': (816, 256),
                        'name': 'beedleshipspawner7',
                        'offsetkey': 'beedleshipspawner',
                        'scripts': 'beedleshipspawner',
                        'sprites': 'beedleshipspawner',
                        'tangible': False},
 'beedleshipspawner8': {'DIM': (48, 48),
                        'POS': (352, 320),
                        'name': 'beedleshipspawner8',
                        'offsetkey': 'beedleshipspawner',
                        'scripts': 'beedleshipspawner',
                        'sprites': 'beedleshipspawner',
                        'tangible': False},
 'beedleshipspawner9': {'DIM': (48, 48),
                        'POS': (816, 320),
                        'name': 'beedleshipspawner9',
                        'offsetkey': 'beedleshipspawner',
                        'scripts': 'beedleshipspawner',
                        'sprites': 'beedleshipspawner',
                        'tangible': False},
 'bgscroller0': {'DIM': (16, 16),
                 'POS': (304, -144),
                 'name': 'bgscroller0',
                 'offsetkey': 'bgscroller',
                 'scripts': 'bgscroller',
                 'sprites': 'bgscroller',
                 'tangible': False},
 'bgscrollerleft0': {'DIM': (16, 16),
                     'POS': (48, 208),
                     'name': 'bgscrollerleft0',
                     'offsetkey': 'bgscrollerleft',
                     'scripts': 'bgscrollerleft',
                     'sprites': 'bgscrollerleft',
                     'tangible': False},
 'bossarms0': {'DIM': (48, 48),
               'POS': (320, 336),
               'name': 'bossarms0',
               'offsetkey': 'bossarms',
               'scripts': 'bossarms',
               'sprites': 'bossarms',
               'tangible': False},
 'bossbody0': {'DIM': (48, 48),
               'POS': (320, 336),
               'name': 'bossbody0',
               'offsetkey': 'bossbody',
               'scripts': 'bossbody',
               'sprites': 'bossbody',
               'tangible': False},
 'bosshead0': {'DIM': (64, 64),
               'POS': (304, 272),
               'name': 'bosshead0',
               'offsetkey': 'bosshead',
               'scripts': 'bosshead',
               'sprites': 'bosshead',
               'tangible': False},
 'bosspawner0': {'DIM': (64, 64),
                 'POS': (576, 64),
                 'name': 'bosspawner0',
                 'offsetkey': 'bosspawner',
                 'scripts': 'bosspawner',
                 'sprites': 'bosspawner',
                 'tangible': False},
 'bowlershot0': {'DIM': (48, 48),
                 'POS': (560, 176),
                 'name': 'bowlershot0',
                 'offsetkey': 'bowlershot',
                 'scripts': 'bowlershot',
                 'sprites': 'bowlershot',
                 'tangible': False},
 'bulletclear0': {'DIM': (1152, 96),
                  'POS': (0, -96),
                  'name': 'bulletclear0',
                  'offsetkey': 'bulletclear',
                  'scripts': 'bulletclear',
                  'sprites': 'bulletclear',
                  'tangible': False},
 'cautionsign0': {'DIM': (112, 32),
                  'POS': (80, 48),
                  'name': 'cautionsign0',
                  'offsetkey': 'cautionsign',
                  'scripts': 'cautionsign',
                  'sprites': 'cautionsign',
                  'tangible': False},
 'controllermanager0': {'DIM': (16, 16),
                        'POS': (752, 128),
                        'name': 'controllermanager0',
                        'offsetkey': 'controllermanager',
                        'scripts': 'controllermanager',
                        'sprites': 'controllermanager',
                        'tangible': False},
 'destroyer0': {'DIM': (128, 128),
                'POS': (96, 80),
                'name': 'destroyer0',
                'offsetkey': 'destroyer',
                'scripts': 'destroyer',
                'sprites': 'destroyer',
                'tangible': False},
 'destroyerspawner0': {'DIM': (128, 128),
                       'POS': (672, 64),
                       'name': 'destroyerspawner0',
                       'offsetkey': 'destroyerspawner',
                       'scripts': 'destroyerspawner',
                       'sprites': 'destroyerspawner',
                       'tangible': False},
 'destroyerspawner1': {'DIM': (128, 128),
                       'POS': (416, 64),
                       'name': 'destroyerspawner1',
                       'offsetkey': 'destroyerspawner',
                       'scripts': 'destroyerspawner',
                       'sprites': 'destroyerspawner',
                       'tangible': False},
 'destroyerspawner2': {'DIM': (128, 128),
                       'POS': (464, 208),
                       'name': 'destroyerspawner2',
                       'offsetkey': 'destroyerspawner',
                       'scripts': 'destroyerspawner',
                       'sprites': 'destroyerspawner',
                       'tangible': False},
 'destroyerspawner3': {'DIM': (128, 128),
                       'POS': (624, 208),
                       'name': 'destroyerspawner3',
                       'offsetkey': 'destroyerspawner',
                       'scripts': 'destroyerspawner',
                       'sprites': 'destroyerspawner',
                       'tangible': False},
 'endflavortext0': {'DIM': (1040, 32),
                    'POS': (48, 448),
                    'name': 'endflavortext0',
                    'offsetkey': 'endflavortext',
                    'scripts': 'endflavortext',
                    'sprites': 'endflavortext',
                    'tangible': False},
 'endscenemanager0': {'DIM': (16, 16),
                      'POS': (224, 336),
                      'name': 'endscenemanager0',
                      'offsetkey': 'endscenemanager',
                      'scripts': 'endscenemanager',
                      'sprites': 'endscenemanager',
                      'tangible': False},
 'explode0': {'DIM': (48, 48),
              'POS': (624, 176),
              'name': 'explode0',
              'offsetkey': 'explode',
              'scripts': 'explode',
              'sprites': 'explode',
              'tangible': False},
 'focuson0': {'DIM': (544, 640),
              'POS': (336, 0),
              'name': 'focuson0',
              'offsetkey': 'focuson',
              'scripts': 'focuson',
              'sprites': 'focuson',
              'tangible': False},
 'focuson1': {'DIM': (1152, 640),
              'POS': (0, 0),
              'name': 'focuson1',
              'offsetkey': 'focuson',
              'scripts': 'focuson',
              'sprites': 'focuson',
              'tangible': False},
 'focuson2': {'DIM': (1152, 640),
              'POS': (0, 0),
              'name': 'focuson2',
              'offsetkey': 'focuson',
              'scripts': 'focuson',
              'sprites': 'focuson',
              'tangible': False},
 'fxhit0': {'DIM': (16, 16),
            'POS': (848, 144),
            'name': 'fxhit0',
            'offsetkey': 'fxhit',
            'scripts': 'fxhit',
            'sprites': 'fxhit',
            'tangible': False},
 'inviswall0': {'DIM': (48, 576),
                'POS': (1104, 0),
                'name': 'inviswall0',
                'offsetkey': 'inviswall',
                'scripts': 'inviswall',
                'sprites': 'inviswall',
                'tangible': True},
 'inviswall1': {'DIM': (1056, 48),
                'POS': (48, 0),
                'name': 'inviswall1',
                'offsetkey': 'inviswall',
                'scripts': 'inviswall',
                'sprites': 'inviswall',
                'tangible': True},
 'inviswall2': {'DIM': (48, 576),
                'POS': (0, 0),
                'name': 'inviswall2',
                'offsetkey': 'inviswall',
                'scripts': 'inviswall',
                'sprites': 'inviswall',
                'tangible': True},
 'inviswall4': {'DIM': (64, 272),
                'POS': (0, 208),
                'name': 'inviswall4',
                'offsetkey': 'inviswall',
                'scripts': 'inviswall',
                'sprites': 'inviswall',
                'tangible': True},
 'inviswall5': {'DIM': (1008, 48),
                'POS': (64, 208),
                'name': 'inviswall5',
                'offsetkey': 'inviswall',
                'scripts': 'inviswall',
                'sprites': 'inviswall',
                'tangible': True},
 'inviswall6': {'DIM': (80, 272),
                'POS': (1072, 208),
                'name': 'inviswall6',
                'offsetkey': 'inviswall',
                'scripts': 'inviswall',
                'sprites': 'inviswall',
                'tangible': True},
 'platformrockethudL0': {'DIM': (320, 640),
                         'POS': (288, 0),
                         'name': 'platformrockethudL0',
                         'offsetkey': 'platformrockethudL',
                         'scripts': 'platformrockethudL',
                         'sprites': 'platformrockethudL',
                         'tangible': True},
 'platformrockethudR0': {'DIM': (320, 640),
                         'POS': (608, 0),
                         'name': 'platformrockethudR0',
                         'offsetkey': 'platformrockethudR',
                         'scripts': 'platformrockethudR',
                         'sprites': 'platformrockethudR',
                         'tangible': True},
 'platformrocketmenu0': {'DIM': (1152, 224),
                         'POS': (0, 480),
                         'name': 'platformrocketmenu0',
                         'offsetkey': 'platformrocketmenu',
                         'scripts': 'platformrocketmenu',
                         'sprites': 'platformrocketmenu',
                         'tangible': True},
 'platformrocketmenu1': {'DIM': (640, 64),
                         'POS': (288, -64),
                         'name': 'platformrocketmenu1',
                         'offsetkey': 'platformrocketmenu',
                         'scripts': 'platformrocketmenu',
                         'sprites': 'platformrocketmenu',
                         'tangible': True},
 'platformrocketmenu2': {'DIM': (640, 64),
                         'POS': (288, 640),
                         'name': 'platformrocketmenu2',
                         'offsetkey': 'platformrocketmenu',
                         'scripts': 'platformrocketmenu',
                         'sprites': 'platformrocketmenu',
                         'tangible': True},
 'powerup0': {'DIM': (48, 48),
              'POS': (784, 128),
              'name': 'powerup0',
              'offsetkey': 'powerup',
              'scripts': 'powerup',
              'sprites': 'powerup',
              'tangible': False},
 'rocketcrow0': {'DIM': (64, 64),
                 'POS': (432, 304),
                 'name': 'rocketcrow0',
                 'offsetkey': 'rocketcrow',
                 'scripts': 'rocketcrow',
                 'sprites': 'rocketcrow',
                 'tangible': True},
 'rocketcrowspawner0': {'DIM': (64, 64),
                        'POS': (752, 64),
                        'name': 'rocketcrowspawner0',
                        'offsetkey': 'rocketcrowspawner',
                        'scripts': 'rocketcrowspawner',
                        'sprites': 'rocketcrowspawner',
                        'tangible': False},
 'rocketcrowspawner1': {'DIM': (64, 64),
                        'POS': (400, 64),
                        'name': 'rocketcrowspawner1',
                        'offsetkey': 'rocketcrowspawner',
                        'scripts': 'rocketcrowspawner',
                        'sprites': 'rocketcrowspawner',
                        'tangible': False},
 'rocketgamemanager0': {'DIM': (16, 16),
                        'POS': (336, -144),
                        'name': 'rocketgamemanager0',
                        'offsetkey': 'rocketgamemanager',
                        'scripts': 'rocketgamemanager',
                        'sprites': 'rocketgamemanager',
                        'tangible': False},
 'rockethpbarsegment0': {'DIM': (32, 32),
                         'POS': (944, 64),
                         'name': 'rockethpbarsegment0',
                         'offsetkey': 'rockethpbarsegment',
                         'scripts': 'rockethpbarsegment',
                         'sprites': 'rockethpbarsegment',
                         'tangible': False},
 'rockethpbarsegment1': {'DIM': (32, 32),
                         'POS': (976, 64),
                         'name': 'rockethpbarsegment1',
                         'offsetkey': 'rockethpbarsegment',
                         'scripts': 'rockethpbarsegment',
                         'sprites': 'rockethpbarsegment',
                         'tangible': False},
 'rockethpbarsegment10': {'DIM': (32, 32),
                          'POS': (1072, 96),
                          'name': 'rockethpbarsegment10',
                          'offsetkey': 'rockethpbarsegment',
                          'scripts': 'rockethpbarsegment',
                          'sprites': 'rockethpbarsegment',
                          'tangible': False},
 'rockethpbarsegment11': {'DIM': (32, 32),
                          'POS': (1104, 96),
                          'name': 'rockethpbarsegment11',
                          'offsetkey': 'rockethpbarsegment',
                          'scripts': 'rockethpbarsegment',
                          'sprites': 'rockethpbarsegment',
                          'tangible': False},
 'rockethpbarsegment2': {'DIM': (32, 32),
                         'POS': (1008, 64),
                         'name': 'rockethpbarsegment2',
                         'offsetkey': 'rockethpbarsegment',
                         'scripts': 'rockethpbarsegment',
                         'sprites': 'rockethpbarsegment',
                         'tangible': False},
 'rockethpbarsegment3': {'DIM': (32, 32),
                         'POS': (1040, 64),
                         'name': 'rockethpbarsegment3',
                         'offsetkey': 'rockethpbarsegment',
                         'scripts': 'rockethpbarsegment',
                         'sprites': 'rockethpbarsegment',
                         'tangible': False},
 'rockethpbarsegment4': {'DIM': (32, 32),
                         'POS': (1072, 64),
                         'name': 'rockethpbarsegment4',
                         'offsetkey': 'rockethpbarsegment',
                         'scripts': 'rockethpbarsegment',
                         'sprites': 'rockethpbarsegment',
                         'tangible': False},
 'rockethpbarsegment5': {'DIM': (32, 32),
                         'POS': (1104, 64),
                         'name': 'rockethpbarsegment5',
                         'offsetkey': 'rockethpbarsegment',
                         'scripts': 'rockethpbarsegment',
                         'sprites': 'rockethpbarsegment',
                         'tangible': False},
 'rockethpbarsegment6': {'DIM': (32, 32),
                         'POS': (944, 96),
                         'name': 'rockethpbarsegment6',
                         'offsetkey': 'rockethpbarsegment',
                         'scripts': 'rockethpbarsegment',
                         'sprites': 'rockethpbarsegment',
                         'tangible': False},
 'rockethpbarsegment7': {'DIM': (32, 32),
                         'POS': (976, 96),
                         'name': 'rockethpbarsegment7',
                         'offsetkey': 'rockethpbarsegment',
                         'scripts': 'rockethpbarsegment',
                         'sprites': 'rockethpbarsegment',
                         'tangible': False},
 'rockethpbarsegment8': {'DIM': (32, 32),
                         'POS': (1008, 96),
                         'name': 'rockethpbarsegment8',
                         'offsetkey': 'rockethpbarsegment',
                         'scripts': 'rockethpbarsegment',
                         'sprites': 'rockethpbarsegment',
                         'tangible': False},
 'rockethpbarsegment9': {'DIM': (32, 32),
                         'POS': (1040, 96),
                         'name': 'rockethpbarsegment9',
                         'offsetkey': 'rockethpbarsegment',
                         'scripts': 'rockethpbarsegment',
                         'sprites': 'rockethpbarsegment',
                         'tangible': False},
 'rockethpdisplay0': {'DIM': (192, 64),
                      'POS': (944, 64),
                      'name': 'rockethpdisplay0',
                      'offsetkey': 'rockethpdisplay',
                      'scripts': 'rockethpdisplay',
                      'sprites': 'rockethpdisplay',
                      'tangible': False},
 'rockethpmanager0': {'DIM': (16, 16),
                      'POS': (896, 64),
                      'name': 'rockethpmanager0',
                      'offsetkey': 'rockethpmanager',
                      'scripts': 'rockethpmanager',
                      'sprites': 'rockethpmanager',
                      'tangible': False},
 'rockethudblinker0': {'DIM': (80, 80),
                       'POS': (96, 512),
                       'name': 'rockethudblinker0',
                       'offsetkey': 'rockethudblinker',
                       'scripts': 'rockethudblinker',
                       'sprites': 'rockethudblinker',
                       'tangible': False},
 'rockethudblinker1': {'DIM': (80, 80),
                       'POS': (96, 368),
                       'name': 'rockethudblinker1',
                       'offsetkey': 'rockethudblinker',
                       'scripts': 'rockethudblinker',
                       'sprites': 'rockethudblinker',
                       'tangible': False},
 'rockethudblinker2': {'DIM': (80, 80),
                       'POS': (96, 224),
                       'name': 'rockethudblinker2',
                       'offsetkey': 'rockethudblinker',
                       'scripts': 'rockethudblinker',
                       'sprites': 'rockethudblinker',
                       'tangible': False},
 'rockethudblinker3': {'DIM': (80, 80),
                       'POS': (96, 80),
                       'name': 'rockethudblinker3',
                       'offsetkey': 'rockethudblinker',
                       'scripts': 'rockethudblinker',
                       'sprites': 'rockethudblinker',
                       'tangible': False},
 'rocketmenugerder0': {'DIM': (16, 80),
                       'POS': (240, 384),
                       'name': 'rocketmenugerder0',
                       'offsetkey': 'rocketmenugerder',
                       'scripts': 'rocketmenugerder',
                       'sprites': 'rocketmenugerder',
                       'tangible': False},
 'rocketmenustation0': {'DIM': (96, 16),
                        'POS': (160, 464),
                        'name': 'rocketmenustation0',
                        'offsetkey': 'rocketmenustation',
                        'scripts': 'rocketmenustation',
                        'sprites': 'rocketmenustation',
                        'tangible': False},
 'rocketmenutriangle0': {'DIM': (32, 32),
                         'POS': (208, 432),
                         'name': 'rocketmenutriangle0',
                         'offsetkey': 'rocketmenutriangle',
                         'scripts': 'rocketmenutriangle',
                         'sprites': 'rocketmenutriangle',
                         'tangible': False},
 'rocketquitbutton0': {'DIM': (48, 16),
                       'POS': (624, 112),
                       'name': 'rocketquitbutton0',
                       'offsetkey': 'rocketquitbutton',
                       'scripts': 'rocketquitbutton',
                       'sprites': 'rocketquitbutton',
                       'tangible': False},
 'rocketspawnmanager0': {'DIM': (16, 16),
                         'POS': (272, -144),
                         'name': 'rocketspawnmanager0',
                         'offsetkey': 'rocketspawnmanager',
                         'scripts': 'rocketspawnmanager',
                         'sprites': 'rocketspawnmanager',
                         'tangible': False},
 'rocketstartbutton0': {'DIM': (64, 16),
                        'POS': (368, 112),
                        'name': 'rocketstartbutton0',
                        'offsetkey': 'rocketstartbutton',
                        'scripts': 'rocketstartbutton',
                        'sprites': 'rocketstartbutton',
                        'tangible': False},
 'ship0': {'DIM': (48, 64),
           'POS': (592, 544),
           'name': 'ship0',
           'offsetkey': 'ship',
           'scripts': 'ship',
           'sprites': 'ship',
           'tangible': False},
 'ship1': {'DIM': (48, 64),
           'POS': (192, 400),
           'name': 'ship1',
           'offsetkey': 'ship',
           'scripts': 'ship',
           'sprites': 'ship',
           'tangible': False},
 'ship2': {'DIM': (48, 64),
           'POS': (544, 432),
           'name': 'ship2',
           'offsetkey': 'ship',
           'scripts': 'ship',
           'sprites': 'ship',
           'tangible': False},
 'smokeball0': {'DIM': (48, 48),
                'POS': (688, 176),
                'name': 'smokeball0',
                'offsetkey': 'smokeball',
                'scripts': 'smokeball',
                'sprites': 'smokeball',
                'tangible': False},
 'smokeballrev0': {'DIM': (48, 48),
                   'POS': (688, 112),
                   'name': 'smokeballrev0',
                   'offsetkey': 'smokeballrev',
                   'scripts': 'smokeballrev',
                   'sprites': 'smokeballrev',
                   'tangible': False},
 'spacebullet0': {'DIM': (16, 16),
                  'POS': (880, 224),
                  'name': 'spacebullet0',
                  'offsetkey': 'spacebullet',
                  'scripts': 'spacebullet',
                  'sprites': 'spacebullet',
                  'tangible': False},
 'spaceport0': {'DIM': (208, 48),
                'POS': (912, 160),
                'name': 'spaceport0',
                'offsetkey': 'spaceport',
                'scripts': 'spaceport',
                'sprites': 'spaceport',
                'tangible': False},
 'thermometerbottom0': {'DIM': (16, 16),
                        'POS': (896, 224),
                        'name': 'thermometerbottom0',
                        'offsetkey': 'thermometerbottom',
                        'scripts': 'thermometerbottom',
                        'sprites': 'thermometerbottom',
                        'tangible': False},
 'thermometerend0': {'DIM': (16, 16),
                     'POS': (1120, 224),
                     'name': 'thermometerend0',
                     'offsetkey': 'thermometerend',
                     'scripts': 'thermometerend',
                     'sprites': 'thermometerend',
                     'tangible': False},
 'thermometerpiece0': {'DIM': (16, 16),
                       'POS': (928, 224),
                       'name': 'thermometerpiece0',
                       'offsetkey': 'thermometerpiece',
                       'scripts': 'thermometerpiece',
                       'sprites': 'thermometerpiece',
                       'tangible': False},
 'thermometerpiece1': {'DIM': (16, 16),
                       'POS': (944, 224),
                       'name': 'thermometerpiece1',
                       'offsetkey': 'thermometerpiece',
                       'scripts': 'thermometerpiece',
                       'sprites': 'thermometerpiece',
                       'tangible': False},
 'thermometerpiece10': {'DIM': (16, 16),
                        'POS': (1088, 224),
                        'name': 'thermometerpiece10',
                        'offsetkey': 'thermometerpiece',
                        'scripts': 'thermometerpiece',
                        'sprites': 'thermometerpiece',
                        'tangible': False},
 'thermometerpiece11': {'DIM': (16, 16),
                        'POS': (1104, 224),
                        'name': 'thermometerpiece11',
                        'offsetkey': 'thermometerpiece',
                        'scripts': 'thermometerpiece',
                        'sprites': 'thermometerpiece',
                        'tangible': False},
 'thermometerpiece2': {'DIM': (16, 16),
                       'POS': (960, 224),
                       'name': 'thermometerpiece2',
                       'offsetkey': 'thermometerpiece',
                       'scripts': 'thermometerpiece',
                       'sprites': 'thermometerpiece',
                       'tangible': False},
 'thermometerpiece3': {'DIM': (16, 16),
                       'POS': (976, 224),
                       'name': 'thermometerpiece3',
                       'offsetkey': 'thermometerpiece',
                       'scripts': 'thermometerpiece',
                       'sprites': 'thermometerpiece',
                       'tangible': False},
 'thermometerpiece4': {'DIM': (16, 16),
                       'POS': (992, 224),
                       'name': 'thermometerpiece4',
                       'offsetkey': 'thermometerpiece',
                       'scripts': 'thermometerpiece',
                       'sprites': 'thermometerpiece',
                       'tangible': False},
 'thermometerpiece5': {'DIM': (16, 16),
                       'POS': (1008, 224),
                       'name': 'thermometerpiece5',
                       'offsetkey': 'thermometerpiece',
                       'scripts': 'thermometerpiece',
                       'sprites': 'thermometerpiece',
                       'tangible': False},
 'thermometerpiece6': {'DIM': (16, 16),
                       'POS': (1024, 224),
                       'name': 'thermometerpiece6',
                       'offsetkey': 'thermometerpiece',
                       'scripts': 'thermometerpiece',
                       'sprites': 'thermometerpiece',
                       'tangible': False},
 'thermometerpiece7': {'DIM': (16, 16),
                       'POS': (1040, 224),
                       'name': 'thermometerpiece7',
                       'offsetkey': 'thermometerpiece',
                       'scripts': 'thermometerpiece',
                       'sprites': 'thermometerpiece',
                       'tangible': False},
 'thermometerpiece8': {'DIM': (16, 16),
                       'POS': (1056, 224),
                       'name': 'thermometerpiece8',
                       'offsetkey': 'thermometerpiece',
                       'scripts': 'thermometerpiece',
                       'sprites': 'thermometerpiece',
                       'tangible': False},
 'thermometerpiece9': {'DIM': (16, 16),
                       'POS': (1072, 224),
                       'name': 'thermometerpiece9',
                       'offsetkey': 'thermometerpiece',
                       'scripts': 'thermometerpiece',
                       'sprites': 'thermometerpiece',
                       'tangible': False},
 'titlecard0': {'DIM': (256, 80),
                'POS': (880, 16),
                'name': 'titlecard0',
                'offsetkey': 'titlecard',
                'scripts': 'titlecard',
                'sprites': 'titlecard',
                'tangible': False},
 'triangleman0': {'DIM': (48, 48),
                  'POS': (240, 80),
                  'name': 'triangleman0',
                  'offsetkey': 'triangleman',
                  'scripts': 'triangleman',
                  'sprites': 'triangleman',
                  'tangible': False},
 'trianglespawner0': {'DIM': (48, 48),
                      'POS': (608, 0),
                      'name': 'trianglespawner0',
                      'offsetkey': 'trianglespawner',
                      'scripts': 'trianglespawner',
                      'sprites': 'trianglespawner',
                      'tangible': False},
 'trianglespawner1': {'DIM': (48, 48),
                      'POS': (560, 0),
                      'name': 'trianglespawner1',
                      'offsetkey': 'trianglespawner',
                      'scripts': 'trianglespawner',
                      'sprites': 'trianglespawner',
                      'tangible': False},
 'trianglespawner2': {'DIM': (48, 48),
                      'POS': (656, 0),
                      'name': 'trianglespawner2',
                      'offsetkey': 'trianglespawner',
                      'scripts': 'trianglespawner',
                      'sprites': 'trianglespawner',
                      'tangible': False},
 'trianglespawner3': {'DIM': (48, 48),
                      'POS': (512, 0),
                      'name': 'trianglespawner3',
                      'offsetkey': 'trianglespawner',
                      'scripts': 'trianglespawner',
                      'sprites': 'trianglespawner',
                      'tangible': False},
 'trianglespawner4': {'DIM': (48, 48),
                      'POS': (704, 0),
                      'name': 'trianglespawner4',
                      'offsetkey': 'trianglespawner',
                      'scripts': 'trianglespawner',
                      'sprites': 'trianglespawner',
                      'tangible': False},
 'trianglespawner5': {'DIM': (48, 48),
                      'POS': (464, 0),
                      'name': 'trianglespawner5',
                      'offsetkey': 'trianglespawner',
                      'scripts': 'trianglespawner',
                      'sprites': 'trianglespawner',
                      'tangible': False},
 'trianglespawner6': {'DIM': (48, 48),
                      'POS': (752, 0),
                      'name': 'trianglespawner6',
                      'offsetkey': 'trianglespawner',
                      'scripts': 'trianglespawner',
                      'sprites': 'trianglespawner',
                      'tangible': False},
 'trianglespawner7': {'DIM': (48, 48),
                      'POS': (416, 0),
                      'name': 'trianglespawner7',
                      'offsetkey': 'trianglespawner',
                      'scripts': 'trianglespawner',
                      'sprites': 'trianglespawner',
                      'tangible': False},
 'trianglespawner8': {'DIM': (48, 48),
                      'POS': (800, 0),
                      'name': 'trianglespawner8',
                      'offsetkey': 'trianglespawner',
                      'scripts': 'trianglespawner',
                      'sprites': 'trianglespawner',
                      'tangible': False},
 'trianglespawner9': {'DIM': (48, 48),
                      'POS': (368, 0),
                      'name': 'trianglespawner9',
                      'offsetkey': 'trianglespawner',
                      'scripts': 'trianglespawner',
                      'sprites': 'trianglespawner',
                      'tangible': False},
 'youwin0': {'DIM': (256, 48),
             'POS': (240, 384),
             'name': 'youwin0',
             'offsetkey': 'youwin',
             'scripts': 'youwin',
             'sprites': 'youwin',
             'tangible': False}}