ACTORS = {'bgscroller0': {'DIM': (16, 16),
                 'POS': (16, 80),
                 'name': 'bgscroller0',
                 'offsetkey': 'bgscroller',
                 'scripts': 'bgscroller',
                 'sprites': 'bgscroller',
                 'tangible': False},
 'explode0': {'DIM': (48, 48),
              'POS': (1280, 288),
              'name': 'explode0',
              'offsetkey': 'explode',
              'scripts': 'explode',
              'sprites': 'explode',
              'tangible': False},
 'fxhit0': {'DIM': (16, 16),
            'POS': (1360, 288),
            'name': 'fxhit0',
            'offsetkey': 'fxhit',
            'scripts': 'fxhit',
            'sprites': 'fxhit',
            'tangible': False},
 'powerup0': {'DIM': (48, 48),
              'POS': (928, 48),
              'name': 'powerup0',
              'offsetkey': 'powerup',
              'scripts': 'powerup',
              'sprites': 'powerup',
              'tangible': False},
 'powerup2': {'DIM': (48, 48),
              'POS': (624, 112),
              'name': 'powerup2',
              'offsetkey': 'powerup',
              'scripts': 'powerup',
              'sprites': 'powerup',
              'tangible': False},
 'powerup3': {'DIM': (48, 48),
              'POS': (304, 96),
              'name': 'powerup3',
              'offsetkey': 'powerup',
              'scripts': 'powerup',
              'sprites': 'powerup',
              'tangible': False},
 'ship0': {'DIM': (48, 64),
           'POS': (464, 464),
           'name': 'ship0',
           'offsetkey': 'ship',
           'scripts': 'ship',
           'sprites': 'ship',
           'tangible': False},
 'smokeball0': {'DIM': (48, 48),
                'POS': (464, 512),
                'name': 'smokeball0',
                'offsetkey': 'smokeball',
                'scripts': 'smokeball',
                'sprites': 'smokeball',
                'tangible': False},
 'spacebullet0': {'DIM': (16, 16),
                  'POS': (560, 432),
                  'name': 'spacebullet0',
                  'offsetkey': 'spacebullet',
                  'scripts': 'spacebullet',
                  'sprites': 'spacebullet',
                  'tangible': False},
 'triangleman0': {'DIM': (48, 48),
                  'POS': (32, 32),
                  'name': 'triangleman0',
                  'offsetkey': 'triangleman',
                  'scripts': 'triangleman',
                  'sprites': 'triangleman',
                  'tangible': False},
 'triangleman1': {'DIM': (48, 48),
                  'POS': (160, 32),
                  'name': 'triangleman1',
                  'offsetkey': 'triangleman',
                  'scripts': 'triangleman',
                  'sprites': 'triangleman',
                  'tangible': False},
 'triangleman2': {'DIM': (48, 48),
                  'POS': (320, 32),
                  'name': 'triangleman2',
                  'offsetkey': 'triangleman',
                  'scripts': 'triangleman',
                  'sprites': 'triangleman',
                  'tangible': False},
 'triangleman3': {'DIM': (48, 48),
                  'POS': (448, 32),
                  'name': 'triangleman3',
                  'offsetkey': 'triangleman',
                  'scripts': 'triangleman',
                  'sprites': 'triangleman',
                  'tangible': False},
 'triangleman4': {'DIM': (48, 48),
                  'POS': (608, 32),
                  'name': 'triangleman4',
                  'offsetkey': 'triangleman',
                  'scripts': 'triangleman',
                  'sprites': 'triangleman',
                  'tangible': False},
 'triangleman5': {'DIM': (48, 48),
                  'POS': (720, 32),
                  'name': 'triangleman5',
                  'offsetkey': 'triangleman',
                  'scripts': 'triangleman',
                  'sprites': 'triangleman',
                  'tangible': False},
 'triangleman6': {'DIM': (48, 48),
                  'POS': (864, 32),
                  'name': 'triangleman6',
                  'offsetkey': 'triangleman',
                  'scripts': 'triangleman',
                  'sprites': 'triangleman',
                  'tangible': False},
 'triangleman7': {'DIM': (48, 48),
                  'POS': (992, 32),
                  'name': 'triangleman7',
                  'offsetkey': 'triangleman',
                  'scripts': 'triangleman',
                  'sprites': 'triangleman',
                  'tangible': False}}