HITBOXES = {'beedleship': {'FLY:0': [], 'FLYLEFT:0': [], 'FLYRIGHT:0': [], 'START:0': []},
 'rocketbowlershot': {'BBALL:0': [((7, 5), (34, 39))], 'START:0': []},
 'rocketdestroyer': {'FLY:0': [], 'START:0': []},
 'ship': {'BROKE:0': [],
          'FLY:0': [],
          'FLYLEFT:0': [],
          'FLYRIGHT:0': [],
          'START:0': []},
 'spacebullet': {'BALL:0': [((2, 2), (12, 12))],
                 'BEAM:0': [((-29, 2), (75, 26))],
                 'CROSS:0': [((2, 2), (12, 12))],
                 'SHOT:0': [((3, 4), (10, 9))],
                 'SQUIG:0': [((5, 0), (6, 32))],
                 'SQUIG:5': [((1, 3), (6, 13)), ((9, 17), (6, 12))],
                 'START:0': [],
                 'TINY:0': [((0, 0), (4, 9))]},
 'triangle': {'SHIP:0': [], 'START:0': []}}
HURTBOXES = {'beedleship': {'FLY:0': [((3, 11), (42, 31))],
                'FLYLEFT:0': [((1, 11), (42, 34))],
                'FLYRIGHT:0': [((6, 11), (41, 31))],
                'START:0': []},
 'rocketbowlershot': {'BBALL:0': [], 'START:0': []},
 'rocketdestroyer': {'FLY:0': [((11, 27), (106, 27))], 'START:0': []},
 'ship': {'BROKE:0': [],
          'FLY:0': [((18, 19), (12, 10))],
          'FLYLEFT:0': [((18, 19), (12, 10))],
          'FLYRIGHT:0': [((18, 19), (12, 10))],
          'START:0': []},
 'spacebullet': {'BALL:0': [],
                 'BEAM:0': [],
                 'CROSS:0': [],
                 'SHOT:0': [],
                 'SQUIG:0': [],
                 'SQUIG:5': [],
                 'START:0': [],
                 'TINY:0': []},
 'triangle': {'SHIP:0': [((0, 2), (48, 10))], 'START:0': []}}