SCRIPTS = {'beedleship': {'BROKE:0': [['exec', 'explode']],
                'BROKE:60': [['goodbye']],
                'BYE:0': [['goodbye']],
                'FLY:0': [['exec', 'updateSmoke'],
                          ['set', 'self', 'x_vel', '0'],
                          ['exec', 'updateShot']],
                'FLY:16': [['exec', 'updateSmoke'],
                           ['set', 'self', 'state', 'self.flydir'],
                           ['set', 'self', 'frame', '0']],
                'FLYLEFT:0': [['exec', 'updateSmoke'],
                              ['set',
                               'self',
                               'x_vel',
                               'self.speed',
                               '*',
                               '-1']],
                'FLYLEFT:16': [['exec', 'updateSmoke'],
                               ['set', 'self', 'frame', '0'],
                               ['set', 'self', 'state', 'FLY']],
                'FLYRIGHT:0': [['exec', 'updateSmoke'],
                               ['set', 'self', 'x_vel', 'self.speed']],
                'FLYRIGHT:16': [['exec', 'updateSmoke'],
                                ['set', 'self', 'frame', '0'],
                                ['set', 'self', 'state', 'FLY']],
                'START:0': [['set', 'self', 'physics', '1'],
                            ['set', 'self', 'state', 'FLY'],
                            ['set', 'self', 'bulletfreq', '5'],
                            ['set', 'self', 'bulletcounter', '4'],
                            ['set', 'self', 'bulletnum', '0'],
                            ['set', 'self', 'bulletmax', '21'],
                            ['set', 'self', 'shotspeed', '3'],
                            ['set', 'self', 'smokenum', '0'],
                            ['set', 'self', 'smokemax', '8'],
                            ['set', 'self', 'smokecounter', '0'],
                            ['set', 'self', 'smokefreq', '8'],
                            ['set', 'self', 'flydir', 'FLYLEFT'],
                            ['set', 'self', 'speed', '2'],
                            ['hitboxes', 'beedleship'],
                            ['hurtboxes', 'beedleship'],
                            ['set', 'self', 'explodenum', '0'],
                            ['set', 'self', 'explodemax', '8'],
                            ['set', 'self', 'explodecounter', '0'],
                            ['set', 'self', 'explodefreq', '8'],
                            ['set', 'self', 'hp', '6']],
                'XCOLLISION': [['set', 'self', 'calc', 'self.flydir'],
                               ['if', 'self.calc', '==', 'FLYLEFT'],
                               ['set', 'self', 'flydir', 'FLYRIGHT'],
                               ['set', 'self', 'state', 'FLYRIGHT'],
                               ['endif'],
                               ['if', 'self.calc', '==', 'FLYRIGHT'],
                               ['set', 'self', 'flydir', 'FLYLEFT'],
                               ['set', 'self', 'state', 'FLYLEFT'],
                               ['endif']],
                'explode': [['if',
                             'self.explodecounter',
                             '==',
                             'self.explodefreq'],
                            ['set', 'self', 'explodecounter', '0'],
                            ['set', 'self', '_x', 'self.x'],
                            ['set', 'self', '_y', 'self.y'],
                            ['for', 'i', 'range', '3'],
                            ['set',
                             'self',
                             '_x',
                             'RAND?',
                             '*',
                             '-16',
                             '+',
                             'self._x'],
                            ['set',
                             'self',
                             '_x',
                             'RAND?',
                             '*',
                             '-3',
                             '+',
                             'self._x'],
                            ['set',
                             'self',
                             '_x',
                             'RAND?',
                             '*',
                             '16',
                             '+',
                             'self._x'],
                            ['set',
                             'self',
                             '_x',
                             'RAND?',
                             '*',
                             '3',
                             '+',
                             'self._x'],
                            ['set',
                             'self',
                             '_y',
                             'RAND?',
                             '*',
                             '-16',
                             '+',
                             'self._y'],
                            ['set',
                             'self',
                             '_y',
                             'RAND?',
                             '*',
                             '-3',
                             '+',
                             'self._y'],
                            ['set',
                             'self',
                             '_y',
                             'RAND?',
                             '*',
                             '16',
                             '+',
                             'self._y'],
                            ['set',
                             'self',
                             '_y',
                             'RAND?',
                             '*',
                             '-3',
                             '+',
                             'self._y'],
                            ['endfor'],
                            ['create',
                             'explode0',
                             'self.name',
                             '+',
                             'explode',
                             '+',
                             'self.explodenum',
                             'self._x',
                             'self._y'],
                            ['set',
                             'self',
                             'explodenum',
                             'self.explodenum',
                             '+',
                             '1'],
                            ['endif'],
                            ['set',
                             'self',
                             'explodecounter',
                             'self.explodecounter',
                             '+',
                             '1']],
                'shoot': [['set',
                           'self',
                           'bulletname',
                           'self.name',
                           '+',
                           'bullet',
                           '+',
                           'self.bulletnum'],
                          ['create',
                           'spacebullet0',
                           'self.bulletname',
                           'self.w',
                           '/',
                           '2',
                           '+',
                           'self.x',
                           '-',
                           '8',
                           'self.y',
                           '+',
                           '48'],
                          ['set', 'self.bulletname', 'state', 'CROSS'],
                          ['set', 'self.bulletname', 'y_vel', 'self.shotspeed'],
                          ['set',
                           'self',
                           'bulletnum',
                           'self.bulletnum',
                           '+',
                           '1'],
                          ['if', 'self.bulletnum', '==', 'self.bulletmax'],
                          ['set', 'self', 'bulletnum', '0'],
                          ['endif']],
                'updateShot': [['if',
                                'self.bulletcounter',
                                '>=',
                                'self.bulletfreq'],
                               ['exec', 'shoot'],
                               ['set', 'self', 'bulletcounter', '0'],
                               ['endif'],
                               ['set',
                                'self',
                                'bulletcounter',
                                'self.bulletcounter',
                                '+',
                                '1']],
                'updateSmoke': [['if',
                                 'self.smokecounter',
                                 '==',
                                 'self.smokefreq'],
                                ['set', 'self', 'smokecounter', '0'],
                                ['create',
                                 'smokeballrev0',
                                 'self.name',
                                 '+',
                                 'smokeball',
                                 '+',
                                 'self.smokenum',
                                 'self.x',
                                 '+',
                                 'RAND?',
                                 '+',
                                 'RAND?',
                                 '-',
                                 'RAND?',
                                 '-',
                                 'RAND?',
                                 'self.y'],
                                ['set',
                                 'self',
                                 'smokenum',
                                 'self.smokenum',
                                 '+',
                                 '1'],
                                ['if', 'self.smokenum', '==', 'self.smokemax'],
                                ['set', 'self', 'smokenum', '0'],
                                ['endif'],
                                ['endif'],
                                ['set',
                                 'self',
                                 'smokecounter',
                                 'self.smokecounter',
                                 '+',
                                 '1']]},
 'beedleshipspawner': {'SPAWN:0': [['set', 'self', 'state', 'WAIT'],
                                   ['if', 'exists', 'self.spawnname'],
                                   ['break'],
                                   ['endif'],
                                   ['create',
                                    'beedleship0',
                                    'self.spawnname',
                                    'self.x',
                                    'self.y']],
                       'START:0': [['set', 'self', 'state', 'WAIT'],
                                   ['set',
                                    'self',
                                    'spawnname',
                                    'self.name',
                                    '+',
                                    'beedleship']]},
 'bgscroller': {'SCROLL:0': [['offsetbgscrolly', 'WORLD?', 'self.scroll_y'],
                             ['offsetbgscrollx', 'WORLD?', 'self.scroll_x']],
                'START:0': [['set', 'self', 'scroll_x', '0'],
                            ['set', 'self', 'scroll_y', '0'],
                            ['set', 'self', 'state', 'SCROLL']]},
 'bgscrollerleft': {'START:0': [['offsetbgscrollx', 'WORLD?', '-1']]},
 'bowlershot': {'BBALL:0': [['exec', 'applyTraction']],
                'BBALL:16': [['set', 'self', 'frame', '0'],
                             ['exec', 'BBALL:0']],
                'EXPLODE:0': [['set',
                               'self',
                               'bname',
                               'self.name',
                               '+',
                               'bullet0'],
                              ['create',
                               'spacebullet0',
                               'self.bname',
                               'self.x',
                               'self.y'],
                              ['set',
                               'self.bname',
                               'x_vel',
                               '0',
                               '-',
                               'self.shotspeed'],
                              ['set',
                               'self.bname',
                               'y_vel',
                               '0',
                               '-',
                               'self.shotspeed'],
                              ['set', 'self.bname', 'state', 'BALL'],
                              ['set',
                               'self',
                               'bname',
                               'self.name',
                               '+',
                               'bullet1'],
                              ['create',
                               'spacebullet0',
                               'self.bname',
                               'self.x',
                               'self.y'],
                              ['set', 'self.bname', 'x_vel', 'self.shotspeed'],
                              ['set',
                               'self.bname',
                               'y_vel',
                               '0',
                               '-',
                               'self.shotspeed'],
                              ['set', 'self.bname', 'state', 'BALL'],
                              ['set',
                               'self',
                               'bname',
                               'self.name',
                               '+',
                               'bullet2'],
                              ['create',
                               'spacebullet0',
                               'self.bname',
                               'self.x',
                               'self.y'],
                              ['set',
                               'self.bname',
                               'x_vel',
                               '0',
                               '-',
                               'self.shotspeed'],
                              ['set', 'self.bname', 'y_vel', '0'],
                              ['set', 'self.bname', 'state', 'BALL'],
                              ['set',
                               'self',
                               'bname',
                               'self.name',
                               '+',
                               'bullet3'],
                              ['create',
                               'spacebullet0',
                               'self.bname',
                               'self.x',
                               'self.y'],
                              ['set', 'self.bname', 'x_vel', 'self.shotspeed'],
                              ['set', 'self.bname', 'y_vel', '0'],
                              ['set', 'self.bname', 'state', 'BALL'],
                              ['set',
                               'self',
                               'bname',
                               'self.name',
                               '+',
                               'bullet4'],
                              ['create',
                               'spacebullet0',
                               'self.bname',
                               'self.x',
                               'self.y'],
                              ['set',
                               'self.bname',
                               'x_vel',
                               '0',
                               '-',
                               'self.shotspeed'],
                              ['set', 'self.bname', 'y_vel', 'self.shotspeed'],
                              ['set', 'self.bname', 'state', 'BALL'],
                              ['set',
                               'self',
                               'bname',
                               'self.name',
                               '+',
                               'bullet5'],
                              ['create',
                               'spacebullet0',
                               'self.bname',
                               'self.x',
                               'self.y'],
                              ['set',
                               'self.bname',
                               'x_vel',
                               '0',
                               '+',
                               'self.shotspeed'],
                              ['set', 'self.bname', 'y_vel', 'self.shotspeed'],
                              ['set', 'self.bname', 'state', 'BALL'],
                              ['set',
                               'self',
                               'bname',
                               'self.name',
                               '+',
                               'bullet6'],
                              ['create',
                               'spacebullet0',
                               'self.bname',
                               'self.x',
                               'self.y'],
                              ['set', 'self.bname', 'x_vel', '0'],
                              ['set',
                               'self.bname',
                               'y_vel',
                               '0',
                               '-',
                               'self.shotspeed'],
                              ['set', 'self.bname', 'state', 'BALL'],
                              ['set',
                               'self',
                               'bname',
                               'self.name',
                               '+',
                               'bullet7'],
                              ['create',
                               'spacebullet0',
                               'self.bname',
                               'self.x',
                               'self.y'],
                              ['set', 'self.bname', 'x_vel', '0'],
                              ['set', 'self.bname', 'y_vel', 'self.shotspeed'],
                              ['set', 'self.bname', 'state', 'BALL'],
                              ['goodbye']],
                'START:0': [['set', 'self', 'state', 'BBALL'],
                            ['set', 'self', 'physics', '1'],
                            ['set', 'self', 'traction', '0.9'],
                            ['set', 'self', 'shotspeed', '4'],
                            ['set',
                             'self',
                             'x_vel',
                             'ship0.x',
                             '-',
                             'self.x',
                             '/',
                             '10'],
                            ['set',
                             'self',
                             'y_vel',
                             'ship0.y',
                             '-',
                             'self.y',
                             '/',
                             '10'],
                            ['hitboxes', 'rocketbowlershot'],
                            ['hurtboxes', 'rocketbowlershot']],
                'applyTraction': [['set',
                                   'self',
                                   'x_vel',
                                   'self.x_vel',
                                   '*',
                                   'self.traction'],
                                  ['set',
                                   'self',
                                   'y_vel',
                                   'self.y_vel',
                                   '*',
                                   'self.traction'],
                                  ['set',
                                   'self',
                                   'calc',
                                   'abs',
                                   'self.x_vel',
                                   '<',
                                   '0.1'],
                                  ['if',
                                   'abs',
                                   'self.y_vel',
                                   '<',
                                   '0.1',
                                   'and',
                                   'self.calc'],
                                  ['set', 'self', 'y_vel', '0'],
                                  ['set', 'self', 'state', 'EXPLODE'],
                                  ['endif']]},
 'bulletclear': {'COLLIDE': [['set', 'self', 'state', 'BYE']]},
 'destroyer': {'BROKE:0': [['exec', 'explode']],
               'BROKE:60': [['goodbye']],
               'BYE:0': [['goodbye']],
               'FLY:0': [['exec', 'updateSmoke'], ['exec', 'updateShot']],
               'START:0': [['set', 'self', 'state', 'FLY'],
                           ['set', 'self', 'bulletfreq', '90'],
                           ['set', 'self', 'bulletcounter', '60'],
                           ['set', 'self', 'bulletnum', '0'],
                           ['set', 'self', 'bulletmax', '21'],
                           ['set', 'self', 'shotspeed', '3'],
                           ['set', 'self', 'smokenum', '0'],
                           ['set', 'self', 'smokemax', '8'],
                           ['set', 'self', 'smokecounter', '0'],
                           ['set', 'self', 'smokefreq', '8'],
                           ['set', 'self', 'explodenum', '0'],
                           ['set', 'self', 'explodemax', '8'],
                           ['set', 'self', 'explodecounter', '0'],
                           ['set', 'self', 'explodefreq', '8'],
                           ['set', 'self', 'hp', '16'],
                           ['hitboxes', 'rocketdestroyer'],
                           ['hurtboxes', 'rocketdestroyer']],
               'explode': [['if',
                            'self.explodecounter',
                            '==',
                            'self.explodefreq'],
                           ['set', 'self', 'explodecounter', '0'],
                           ['set',
                            'self',
                            '_x',
                            'self.w',
                            '/',
                            '2',
                            '+',
                            'self.x',
                            '-',
                            '24'],
                           ['set',
                            'self',
                            '_y',
                            'self.h',
                            '/',
                            '2',
                            '+',
                            'self.y',
                            '-',
                            '24'],
                           ['for', 'i', 'range', '5'],
                           ['set',
                            'self',
                            '_x',
                            'RAND?',
                            '*',
                            '-16',
                            '+',
                            'self._x'],
                           ['set',
                            'self',
                            '_x',
                            'RAND?',
                            '*',
                            '-3',
                            '+',
                            'self._x'],
                           ['set',
                            'self',
                            '_x',
                            'RAND?',
                            '*',
                            '16',
                            '+',
                            'self._x'],
                           ['set',
                            'self',
                            '_x',
                            'RAND?',
                            '*',
                            '3',
                            '+',
                            'self._x'],
                           ['set',
                            'self',
                            '_y',
                            'RAND?',
                            '*',
                            '-16',
                            '+',
                            'self._y'],
                           ['set',
                            'self',
                            '_y',
                            'RAND?',
                            '*',
                            '-3',
                            '+',
                            'self._y'],
                           ['set',
                            'self',
                            '_y',
                            'RAND?',
                            '*',
                            '16',
                            '+',
                            'self._y'],
                           ['set',
                            'self',
                            '_y',
                            'RAND?',
                            '*',
                            '-3',
                            '+',
                            'self._y'],
                           ['endfor'],
                           ['create',
                            'explode0',
                            'self.name',
                            '+',
                            'explode',
                            '+',
                            'self.explodenum',
                            'self._x',
                            'self._y'],
                           ['set',
                            'self',
                            'explodenum',
                            'self.explodenum',
                            '+',
                            '1'],
                           ['set',
                            'self',
                            '_x',
                            'self.w',
                            '/',
                            '2',
                            '+',
                            'self.x',
                            '-',
                            '24'],
                           ['set',
                            'self',
                            '_y',
                            'self.h',
                            '/',
                            '2',
                            '+',
                            'self.y',
                            '-',
                            '24'],
                           ['for', 'i', 'range', '5'],
                           ['set',
                            'self',
                            '_x',
                            'RAND?',
                            '*',
                            '-16',
                            '+',
                            'self._x'],
                           ['set',
                            'self',
                            '_x',
                            'RAND?',
                            '*',
                            '-3',
                            '+',
                            'self._x'],
                           ['set',
                            'self',
                            '_x',
                            'RAND?',
                            '*',
                            '16',
                            '+',
                            'self._x'],
                           ['set',
                            'self',
                            '_x',
                            'RAND?',
                            '*',
                            '3',
                            '+',
                            'self._x'],
                           ['set',
                            'self',
                            '_y',
                            'RAND?',
                            '*',
                            '-16',
                            '+',
                            'self._y'],
                           ['set',
                            'self',
                            '_y',
                            'RAND?',
                            '*',
                            '-3',
                            '+',
                            'self._y'],
                           ['set',
                            'self',
                            '_y',
                            'RAND?',
                            '*',
                            '16',
                            '+',
                            'self._y'],
                           ['set',
                            'self',
                            '_y',
                            'RAND?',
                            '*',
                            '-3',
                            '+',
                            'self._y'],
                           ['endfor'],
                           ['create',
                            'explode0',
                            'self.name',
                            '+',
                            'explode',
                            '+',
                            'self.explodenum',
                            'self._x',
                            'self._y'],
                           ['set',
                            'self',
                            'explodenum',
                            'self.explodenum',
                            '+',
                            '1'],
                           ['endif'],
                           ['set',
                            'self',
                            'explodecounter',
                            'self.explodecounter',
                            '+',
                            '1']],
               'shoot': [['set',
                          'self',
                          'bulletname',
                          'self.name',
                          '+',
                          'bullet',
                          '+',
                          'self.bulletnum'],
                         ['create',
                          'bowlershot0',
                          'self.bulletname',
                          'self.w',
                          '/',
                          '2',
                          '+',
                          'self.x',
                          '-',
                          '24',
                          'self.h',
                          '/',
                          '2',
                          '-',
                          '24',
                          '+',
                          'self.y'],
                         ['set',
                          'self',
                          'bulletnum',
                          'self.bulletnum',
                          '+',
                          '1'],
                         ['if', 'self.bulletnum', '==', 'self.bulletmax'],
                         ['set', 'self', 'bulletnum', '0'],
                         ['endif']],
               'updateShot': [['if',
                               'self.bulletcounter',
                               '>=',
                               'self.bulletfreq'],
                              ['exec', 'shoot'],
                              ['set', 'self', 'bulletcounter', '0'],
                              ['endif'],
                              ['set',
                               'self',
                               'bulletcounter',
                               'self.bulletcounter',
                               '+',
                               '1']],
               'updateSmoke': [['if',
                                'self.smokecounter',
                                '==',
                                'self.smokefreq'],
                               ['set', 'self', 'smokecounter', '0'],
                               ['create',
                                'smokeballrev0',
                                'self.name',
                                '+',
                                'smokeball',
                                '+',
                                'self.smokenum',
                                'self.h',
                                '/',
                                '2',
                                '-',
                                '24',
                                '+',
                                'self.x',
                                '+',
                                'RAND?',
                                '+',
                                'RAND?',
                                '-',
                                'RAND?',
                                '-',
                                'RAND?',
                                'self.y'],
                               ['set',
                                'self',
                                'smokenum',
                                'self.smokenum',
                                '+',
                                '1'],
                               ['if', 'self.smokenum', '==', 'self.smokemax'],
                               ['set', 'self', 'smokenum', '0'],
                               ['endif'],
                               ['endif'],
                               ['set',
                                'self',
                                'smokecounter',
                                'self.smokecounter',
                                '+',
                                '1']]},
 'destroyerspawner': {'SPAWN:0': [['set', 'self', 'state', 'WAIT'],
                                  ['if', 'exists', 'self.spawnname'],
                                  ['break'],
                                  ['endif'],
                                  ['create',
                                   'destroyer0',
                                   'self.spawnname',
                                   'self.x',
                                   'self.y']],
                      'START:0': [['set', 'self', 'state', 'WAIT'],
                                  ['set',
                                   'self',
                                   'spawnname',
                                   'self.name',
                                   '+',
                                   'destroyer']]},
 'explode': {'BALL:0': [['set', 'self', 'y', 'self.y', '+', '1']],
             'BALL:45': [['goodbye']],
             'START:0': [['set', 'self', 'state', 'BALL'],
                         ['set', 'self', 'frame', '0']]},
 'focuson': {'START:0': [['focus', 'ROOT', 'self']]},
 'fxhit': {'FX:6': [['goodbye']],
           'START:0': [['set', 'self', 'state', 'FX'],
                       ['set', 'self', 'frame', '0']]},
 'inviswall': {'COLLIDE': [['if', 'CELL', 'in', 'self.name'],
                           ['goodbye'],
                           ['endif']],
               'START:0': [['set', 'self', 'state', 'WALL'],
                           ['set', 'self', 'frame', '0']],
               'WALL:0': [['set', 'self', 'frame', '0']]},
 'platformrockethudL': {'PLATFORM:0': [['if', 'self.shift', '>', '-128'],
                                       ['set',
                                        'self',
                                        'shift',
                                        'self.shift',
                                        '-',
                                        '2'],
                                       ['set', 'self', 'x', 'self.x', '-', '2'],
                                       ['break'],
                                       ['endif'],
                                       ['if', 'self.shift', '>', '-256'],
                                       ['set',
                                        'self',
                                        'shift',
                                        'self.shift',
                                        '-',
                                        '1'],
                                       ['set', 'self', 'x', 'self.x', '-', '1'],
                                       ['break'],
                                       ['endif']],
                        'START:0': [['set', 'self', 'state', 'PLATFORM'],
                                    ['set', 'self', 'platform', '1'],
                                    ['set', 'self', 'startx', 'self.x'],
                                    ['set', 'self', 'starty', 'self.y'],
                                    ['set', 'self', 'frame', '0'],
                                    ['set', 'self', 'shift', '0']]},
 'platformrockethudR': {'PLATFORM:0': [['if', 'self.shift', '<', '128'],
                                       ['set',
                                        'self',
                                        'shift',
                                        'self.shift',
                                        '+',
                                        '2'],
                                       ['set', 'self', 'x', 'self.x', '+', '2'],
                                       ['break'],
                                       ['endif'],
                                       ['if', 'self.shift', '<', '256'],
                                       ['set',
                                        'self',
                                        'shift',
                                        'self.shift',
                                        '+',
                                        '1'],
                                       ['set', 'self', 'x', 'self.x', '+', '1'],
                                       ['break'],
                                       ['endif']],
                        'START:0': [['set', 'self', 'state', 'PLATFORM'],
                                    ['set', 'self', 'platform', '1'],
                                    ['set', 'self', 'startx', 'self.x'],
                                    ['set', 'self', 'starty', 'self.y'],
                                    ['set', 'self', 'frame', '0'],
                                    ['set', 'self', 'shift', '0']]},
 'platformrocketmenu': {'START:0': [['set', 'self', 'state', 'PLATFORM'],
                                    ['set', 'self', 'platform', '1'],
                                    ['set', 'self', 'tangible', '1'],
                                    ['set', 'self', 'frame', '0']]},
 'powerup': {'BYE:0': [['goodbye']],
             'POWERUP:22': [['set', 'self', 'frame', '0']],
             'START:0': [['set', 'self', 'physics', '1'],
                         ['set', 'self', 'y_vel', '2'],
                         ['set', 'self', 'state', 'POWERUP']]},
 'rocketgamemanager': {'PLAY0:0': [['exec', 'checkRestart']],
                       'PLAY0:40': [['add',
                                     'rocketspawnmanager0.funcs',
                                     'trianglesLow'],
                                    ['exec', 'checkRestart']],
                       'PLAY0:42': [['exec', 'checkContinue'],
                                    ['exec', 'checkRestart']],
                       'PLAY1:0': [['exec', 'checkRestart']],
                       'PLAY1:40': [['add',
                                     'rocketspawnmanager0.funcs',
                                     'trianglesLow'],
                                    ['add',
                                     'rocketspawnmanager0.funcs',
                                     'beedlesLow'],
                                    ['exec', 'checkRestart']],
                       'PLAY1:42': [['exec', 'checkContinue'],
                                    ['exec', 'checkRestart']],
                       'PLAY2:0': [['exec', 'checkRestart']],
                       'PLAY2:40': [['add',
                                     'rocketspawnmanager0.funcs',
                                     'destroyerMid'],
                                    ['exec', 'checkRestart']],
                       'PLAY2:42': [['exec', 'checkContinue'],
                                    ['exec', 'checkRestart']],
                       'PLAY3:0': [['exec', 'checkRestart']],
                       'PLAY3:40': [['add',
                                     'rocketspawnmanager0.funcs',
                                     'trianglesMid'],
                                    ['exec', 'checkRestart']],
                       'PLAY3:42': [['exec', 'checkContinue'],
                                    ['exec', 'checkRestart']],
                       'PLAY4:0': [['exec', 'checkRestart']],
                       'PLAY4:40': [['add',
                                     'rocketspawnmanager0.funcs',
                                     'trianglesMid'],
                                    ['exec', 'checkRestart']],
                       'PLAY4:42': [['exec', 'checkRestart']],
                       'PLAY4:55': [['add',
                                     'rocketspawnmanager0.funcs',
                                     'trianglesMidAlt'],
                                    ['exec', 'checkRestart']],
                       'PLAY4:57': [['exec', 'checkContinue']],
                       'PLAY4:60': [['add',
                                     'rocketspawnmanager0.funcs',
                                     'beedlesMid'],
                                    ['exec', 'checkRestart']],
                       'PLAY4:62': [['exec', 'checkContinue'],
                                    ['exec', 'checkRestart']],
                       'PLAY5:0': [['exec', 'checkRestart']],
                       'PLAY5:40': [['add',
                                     'rocketspawnmanager0.funcs',
                                     'trianglesMid'],
                                    ['exec', 'checkRestart']],
                       'PLAY5:42': [['exec', 'checkRestart']],
                       'PLAY5:55': [['add',
                                     'rocketspawnmanager0.funcs',
                                     'destroyerHigh'],
                                    ['exec', 'checkRestart']],
                       'PLAY5:57': [['exec', 'checkContinue'],
                                    ['exec', 'checkRestart']],
                       'PLAY6:60': [['set', 'ship1', 'state', 'WAIT'],
                                    ['view', 'ROOT', 'root'],
                                    ['exec', 'reset']],
                       'START:0': [['set', 'self', 'level', '0'],
                                   ['set',
                                    'self',
                                    'state',
                                    'PLAY',
                                    '+',
                                    'self.level'],
                                   ['set', 'self', 'frame', '0']],
                       'checkContinue': [['set', 'self', 'skip', '0'],
                                         ['for', 'i_', 'range', '10'],
                                         ['set',
                                          'self',
                                          'calc',
                                          'trianglespawner',
                                          '+',
                                          'i_'],
                                         ['set',
                                          'self',
                                          'calc',
                                          'self.calc.spawnname'],
                                         ['if', 'exists', 'self.calc'],
                                         ['set', 'self', 'skip', '1'],
                                         ['break'],
                                         ['endif'],
                                         ['set',
                                          'self',
                                          'calc',
                                          'beedleshipspawner',
                                          '+',
                                          'i_'],
                                         ['set',
                                          'self',
                                          'calc',
                                          'self.calc.spawnname'],
                                         ['if', 'exists', 'self.calc'],
                                         ['set', 'self', 'skip', '1'],
                                         ['break'],
                                         ['endif'],
                                         ['endfor'],
                                         ['for', 'i_', 'range', '4'],
                                         ['set',
                                          'self',
                                          'calc',
                                          'destroyerspawner',
                                          '+',
                                          'i_'],
                                         ['set',
                                          'self',
                                          'calc',
                                          'self.calc.spawnname'],
                                         ['if', 'exists', 'self.calc'],
                                         ['set', 'self', 'skip', '1'],
                                         ['break'],
                                         ['endif'],
                                         ['endfor'],
                                         ['if', 'self.skip'],
                                         ['break'],
                                         ['endif'],
                                         ['set',
                                          'self',
                                          'level',
                                          'self.level',
                                          '+',
                                          '1'],
                                         ['set',
                                          'self',
                                          'state',
                                          'PLAY',
                                          '+',
                                          'self.level'],
                                         ['set', 'self', 'frame', '0'],
                                         ['set',
                                          'bgscroller0',
                                          'scroll_y',
                                          'bgscroller0.scroll_y',
                                          '-',
                                          '1']],
                       'checkRestart': [['set',
                                         'self',
                                         'calc',
                                         'ship0.frame',
                                         '>',
                                         '90'],
                                        ['if',
                                         'ship0.state',
                                         '==',
                                         'BROKE',
                                         'and',
                                         'self.calc'],
                                        ['view', 'ROOT', 'root'],
                                        ['set', 'ship1', 'state', 'WAIT'],
                                        ['exec', 'reset'],
                                        ['endif']],
                       'reset': [['set', 'bgscroller0', 'scroll_y', '0'],
                                 ['set', 'ship0', 'state', 'WAIT'],
                                 ['set', 'ship0', 'frame', '0'],
                                 ['set', 'ship0', 'x', 'ship0.startx'],
                                 ['set', 'ship0', 'y', 'ship0.starty'],
                                 ['set', 'ship0', 'x_vel', '0'],
                                 ['set', 'ship0', 'y_vel', '0'],
                                 ['set', 'ship0', 'level', '0'],
                                 ['set',
                                  'ship0',
                                  'powerupcounter',
                                  'ship0.powerupcountermax'],
                                 ['for', 'i_', 'range', 'ship0.bulletmax'],
                                 ['set',
                                  'self',
                                  '_name',
                                  'ship0bullet',
                                  '+',
                                  'i_'],
                                 ['if', 'exists', 'self._name'],
                                 ['set', 'self._name', 'state', 'BYE'],
                                 ['endif'],
                                 ['endfor'],
                                 ['for', 'i_', 'range', '10'],
                                 ['set',
                                  'self',
                                  'calc',
                                  'trianglespawner',
                                  '+',
                                  'i_'],
                                 ['set', 'self', 'calc', 'self.calc.spawnname'],
                                 ['if', 'exists', 'self.calc'],
                                 ['set', 'self.calc', 'state', 'BYE'],
                                 ['endif'],
                                 ['set',
                                  'self',
                                  'calc',
                                  'beedleshipspawner',
                                  '+',
                                  'i_'],
                                 ['set', 'self', 'calc', 'self.calc.spawnname'],
                                 ['if', 'exists', 'self.calc'],
                                 ['set', 'self.calc', 'state', 'BYE'],
                                 ['endif'],
                                 ['endfor'],
                                 ['for', 'i_', 'range', '4'],
                                 ['set',
                                  'self',
                                  'calc',
                                  'destroyerspawner',
                                  '+',
                                  'i_'],
                                 ['set', 'self', 'calc', 'self.calc.spawnname'],
                                 ['if', 'exists', 'self.calc'],
                                 ['set', 'self.calc', 'state', 'BYE'],
                                 ['endif'],
                                 ['endfor'],
                                 ['set',
                                  'platformrockethudL0',
                                  'x',
                                  'platformrockethudL0.startx'],
                                 ['set',
                                  'platformrockethudL0',
                                  'y',
                                  'platformrockethudL0.starty'],
                                 ['set', 'platformrockethudL0', 'shift', '0'],
                                 ['set',
                                  'platformrockethudR0',
                                  'x',
                                  'platformrockethudR0.startx'],
                                 ['set',
                                  'platformrockethudR0',
                                  'y',
                                  'platformrockethudR0.starty'],
                                 ['set', 'platformrockethudR0', 'shift', '0'],
                                 ['set', 'self', 'frame', '0'],
                                 ['set', 'self', 'state', 'START']]},
 'rocketmenugerder': {'START:0': [['set', 'self', 'state', 'PLAT'],
                                  ['set', 'self', 'tangible', '1']]},
 'rocketmenustation': {'START:0': [['set', 'self', 'state', 'PLAT'],
                                   ['set', 'self', 'tangible', '1']]},
 'rocketmenutriangle': {'START:0': [['set', 'self', 'state', 'PLAT']]},
 'rocketquitbutton': {'COLLIDE': [['quit']],
                      'START:0': [['set', 'self', 'direction', '-1'],
                                  ['set', 'self', 'state', 'BTN']]},
 'rocketspawnmanager': {'PLAY:0': [['set',
                                    'self',
                                    'length',
                                    'len',
                                    'self.funcs'],
                                   ['for', 'i_', 'range', 'self.length'],
                                   ['exec', 'self.funcs', 'at', '0'],
                                   ['remove',
                                    'self.funcs',
                                    'self.funcs',
                                    'at',
                                    '0'],
                                   ['endfor']],
                        'START:0': [['set', 'self', 'funcs', '[]'],
                                    ['set', 'self', 'state', 'PLAY']],
                        'beedlesHigh': [['set',
                                         'beedleshipspawner0',
                                         'state',
                                         'SPAWN'],
                                        ['set',
                                         'beedleshipspawner2',
                                         'state',
                                         'SPAWN'],
                                        ['set',
                                         'beedleshipspawner4',
                                         'state',
                                         'SPAWN'],
                                        ['set',
                                         'beedleshipspawner6',
                                         'state',
                                         'SPAWN'],
                                        ['set',
                                         'beedleshipspawner8',
                                         'state',
                                         'SPAWN'],
                                        ['set',
                                         'beedleshipspawner1',
                                         'state',
                                         'SPAWN'],
                                        ['set',
                                         'beedleshipspawner3',
                                         'state',
                                         'SPAWN'],
                                        ['set',
                                         'beedleshipspawner5',
                                         'state',
                                         'SPAWN'],
                                        ['set',
                                         'beedleshipspawner7',
                                         'state',
                                         'SPAWN'],
                                        ['set',
                                         'beedleshipspawner9',
                                         'state',
                                         'SPAWN']],
                        'beedlesLow': [['set',
                                        'beedleshipspawner0',
                                        'state',
                                        'SPAWN'],
                                       ['set',
                                        'beedleshipspawner1',
                                        'state',
                                        'SPAWN']],
                        'beedlesMid': [['set',
                                        'beedleshipspawner0',
                                        'state',
                                        'SPAWN'],
                                       ['set',
                                        'beedleshipspawner3',
                                        'state',
                                        'SPAWN'],
                                       ['set',
                                        'beedleshipspawner4',
                                        'state',
                                        'SPAWN'],
                                       ['set',
                                        'beedleshipspawner7',
                                        'state',
                                        'SPAWN'],
                                       ['set',
                                        'beedleshipspawner8',
                                        'state',
                                        'SPAWN']],
                        'beedlesMidAlt': [['set',
                                           'beedleshipspawner1',
                                           'state',
                                           'SPAWN'],
                                          ['set',
                                           'beedleshipspawner2',
                                           'state',
                                           'SPAWN'],
                                          ['set',
                                           'beedleshipspawner5',
                                           'state',
                                           'SPAWN'],
                                          ['set',
                                           'beedleshipspawner6',
                                           'state',
                                           'SPAWN'],
                                          ['set',
                                           'beedleshipspawner9',
                                           'state',
                                           'SPAWN']],
                        'destroyerHigh': [['set',
                                           'destroyerspawner0',
                                           'state',
                                           'SPAWN'],
                                          ['set',
                                           'destroyerspawner1',
                                           'state',
                                           'SPAWN'],
                                          ['set',
                                           'destroyerspawner2',
                                           'state',
                                           'SPAWN'],
                                          ['set',
                                           'destroyerspawner3',
                                           'state',
                                           'SPAWN']],
                        'destroyerLow': [['set',
                                          'destroyerspawner0',
                                          'state',
                                          'SPAWN']],
                        'destroyerLowAlt': [['set',
                                             'destroyerspawner1',
                                             'state',
                                             'SPAWN']],
                        'destroyerMid': [['set',
                                          'destroyerspawner0',
                                          'state',
                                          'SPAWN'],
                                         ['set',
                                          'destroyerspawner1',
                                          'state',
                                          'SPAWN']],
                        'destroyerMidAlt': [['set',
                                             'destroyerspawner2',
                                             'state',
                                             'SPAWN'],
                                            ['set',
                                             'destroyerspawner3',
                                             'state',
                                             'SPAWN']],
                        'trianglesHigh': [['set',
                                           'trianglespawner0',
                                           'state',
                                           'SPAWN'],
                                          ['set',
                                           'trianglespawner1',
                                           'state',
                                           'SPAWN'],
                                          ['set',
                                           'trianglespawner2',
                                           'state',
                                           'SPAWN'],
                                          ['set',
                                           'trianglespawner3',
                                           'state',
                                           'SPAWN'],
                                          ['set',
                                           'trianglespawner4',
                                           'state',
                                           'SPAWN'],
                                          ['set',
                                           'trianglespawner5',
                                           'state',
                                           'SPAWN'],
                                          ['set',
                                           'trianglespawner6',
                                           'state',
                                           'SPAWN'],
                                          ['set',
                                           'trianglespawner7',
                                           'state',
                                           'SPAWN'],
                                          ['set',
                                           'trianglespawner8',
                                           'state',
                                           'SPAWN'],
                                          ['set',
                                           'trianglespawner9',
                                           'state',
                                           'SPAWN']],
                        'trianglesLow': [['set',
                                          'trianglespawner2',
                                          'state',
                                          'SPAWN'],
                                         ['set',
                                          'trianglespawner3',
                                          'state',
                                          'SPAWN']],
                        'trianglesMid': [['set',
                                          'trianglespawner1',
                                          'state',
                                          'SPAWN'],
                                         ['set',
                                          'trianglespawner2',
                                          'state',
                                          'SPAWN'],
                                         ['set',
                                          'trianglespawner5',
                                          'state',
                                          'SPAWN'],
                                         ['set',
                                          'trianglespawner6',
                                          'state',
                                          'SPAWN'],
                                         ['set',
                                          'trianglespawner9',
                                          'state',
                                          'SPAWN']],
                        'trianglesMidAlt': [['set',
                                             'trianglespawner0',
                                             'state',
                                             'SPAWN'],
                                            ['set',
                                             'trianglespawner3',
                                             'state',
                                             'SPAWN'],
                                            ['set',
                                             'trianglespawner4',
                                             'state',
                                             'SPAWN'],
                                            ['set',
                                             'trianglespawner7',
                                             'state',
                                             'SPAWN'],
                                            ['set',
                                             'trianglespawner8',
                                             'state',
                                             'SPAWN']]},
 'rocketstartbutton': {'COLLIDE': [['if', 'self.state', '==', 'BYE'],
                                   ['break'],
                                   ['endif'],
                                   ['view', 'ROOT', 'spacelevel'],
                                   ['for', 'i_', 'range', 'ship1.bulletmax'],
                                   ['set',
                                    'self',
                                    '_name',
                                    'ship1bullet',
                                    '+',
                                    'i_'],
                                   ['if', 'exists', 'self._name'],
                                   ['set', 'self._name', 'state', 'BYE'],
                                   ['endif'],
                                   ['endfor']],
                       'START:0': [['set', 'self', 'direction', '-1'],
                                   ['set', 'self', 'state', 'BTN']]},
 'ship': {'BROKE:0': [['exec', 'explode']],
          'COLLIDE': [['if', 'self.state', '==', 'POWERUP'],
                      ['set', 'related', 'level', 'related.level', '+', '1'],
                      ['set', 'related', 'level', 'min', 'related.level', '3'],
                      ['goodbye'],
                      ['endif']],
          'CRASH:0': [['exec', 'applyController'],
                      ['set', 'self', 'state', 'CRASH']],
          'CRASH:32': [['set', 'self', 'state', 'FLY'],
                       ['set', 'self', 'frame', '0']],
          'FLY:0': [['exec', 'applyController'],
                    ['exec', 'updateSmoke'],
                    ['exec', 'updateShot']],
          'FLY:9': [['set', 'self', 'frame', '0'],
                    ['exec', 'applyController'],
                    ['exec', 'updateSmoke'],
                    ['exec', 'updateShot']],
          'FLYLEFT:0': [['exec', 'applyController'],
                        ['exec', 'updateSmoke'],
                        ['exec', 'updateShot']],
          'FLYLEFT:9': [['set', 'self', 'frame', '0'],
                        ['exec', 'applyController'],
                        ['exec', 'updateSmoke'],
                        ['exec', 'updateShot']],
          'FLYRIGHT:0': [['exec', 'applyController'],
                         ['exec', 'updateSmoke'],
                         ['exec', 'updateShot']],
          'FLYRIGHT:9': [['set', 'self', 'frame', '0'],
                         ['exec', 'applyController'],
                         ['exec', 'updateSmoke'],
                         ['exec', 'updateShot']],
          'START:0': [['set', 'self', 'state', 'WAIT'],
                      ['set', 'self', 'startx', 'self.x'],
                      ['set', 'self', 'starty', 'self.y'],
                      ['set', 'self', 'frame', '0'],
                      ['set', 'self', '_input_name', 'PLAYER1'],
                      ['set', 'self', 'regspeed', '6'],
                      ['set', 'self', 'slowspeed', '2'],
                      ['set', 'self', 'tangible', '1'],
                      ['set', 'self', 'smokenum', '0'],
                      ['set', 'self', 'smokemax', '8'],
                      ['set', 'self', 'smokecounter', '0'],
                      ['set', 'self', 'smokefreq', '8'],
                      ['set', 'self', 'bulletnum', '0'],
                      ['set', 'self', 'bulletmax', '80'],
                      ['set', 'self', 'bulletcounter', '0'],
                      ['set', 'self', 'bulletfreq', '10'],
                      ['set', 'self', 'shotspeed', '-8'],
                      ['hitboxes', 'ship'],
                      ['hurtboxes', 'ship'],
                      ['set', 'self', 'level', '0'],
                      ['set', 'self', 'explodenum', '0'],
                      ['set', 'self', 'explodemax', '8'],
                      ['set', 'self', 'explodecounter', '0'],
                      ['set', 'self', 'explodefreq', '8'],
                      ['set', 'self', 'frame_name', 'ROOT'],
                      ['set', 'self', 'powerupcounter', '6'],
                      ['set', 'self', 'powerupcountermax', '6']],
          'WAIT:0': [['exec', 'updateSmoke']],
          'WAIT:30': [['exec', 'updateSmoke'], ['set', 'self', 'state', 'FLY']],
          'applyController': [['set', 'self', 'x_vel', '0'],
                              ['set', 'self', 'y_vel', '0'],
                              ['set', 'self', 'state', 'FLY'],
                              ['set', 'self', 'speed', 'self.regspeed'],
                              ['if', 'inpB'],
                              ['set', 'self', 'speed', 'self.slowspeed'],
                              ['endif'],
                              ['if', 'inpUP'],
                              ['set', 'self', 'y_vel', '0', '-', 'self.speed'],
                              ['endif'],
                              ['if', 'inpDOWN'],
                              ['set', 'self', 'y_vel', 'self.speed'],
                              ['endif'],
                              ['if', 'inpLEFT'],
                              ['set', 'self', 'state', 'FLYLEFT'],
                              ['set', 'self', 'x_vel', '0', '-', 'self.speed'],
                              ['endif'],
                              ['if', 'inpRIGHT'],
                              ['set', 'self', 'state', 'FLYRIGHT'],
                              ['set', 'self', 'x_vel', 'self.speed'],
                              ['endif']],
          'explode': [['if', 'self.explodecounter', '==', 'self.explodefreq'],
                      ['set', 'self', 'explodecounter', '0'],
                      ['set', 'self', '_x', 'self.x'],
                      ['set', 'self', '_y', 'self.y'],
                      ['for', 'i', 'range', '3'],
                      ['set',
                       'self',
                       '_x',
                       'RAND?',
                       '*',
                       '-16',
                       '+',
                       'self._x'],
                      ['set', 'self', '_x', 'RAND?', '*', '-3', '+', 'self._x'],
                      ['set', 'self', '_x', 'RAND?', '*', '16', '+', 'self._x'],
                      ['set', 'self', '_x', 'RAND?', '*', '3', '+', 'self._x'],
                      ['set',
                       'self',
                       '_y',
                       'RAND?',
                       '*',
                       '-16',
                       '+',
                       'self._y'],
                      ['set', 'self', '_y', 'RAND?', '*', '-3', '+', 'self._y'],
                      ['set', 'self', '_y', 'RAND?', '*', '16', '+', 'self._y'],
                      ['set', 'self', '_y', 'RAND?', '*', '-3', '+', 'self._y'],
                      ['endfor'],
                      ['create',
                       'explode0',
                       'self.name',
                       '+',
                       'explode',
                       '+',
                       'self.explodenum',
                       'self._x',
                       'self._y'],
                      ['set',
                       'self',
                       'explodenum',
                       'self.explodenum',
                       '+',
                       '1'],
                      ['endif'],
                      ['set',
                       'self',
                       'explodecounter',
                       'self.explodecounter',
                       '+',
                       '1']],
          'shoot': [['if', 'self.level', '==', '0'],
                    ['set',
                     'self',
                     'bulletname',
                     'self.name',
                     '+',
                     'bullet',
                     '+',
                     'self.bulletnum'],
                    ['create',
                     'spacebullet0',
                     'self.bulletname',
                     'self.w',
                     '/',
                     '2',
                     '+',
                     'self.x',
                     '-',
                     '8',
                     'self.y'],
                    ['set', 'self.bulletname', 'state', 'SHOT'],
                    ['set', 'self.bulletname', 'y_vel', 'self.shotspeed'],
                    ['set', 'self', 'bulletnum', 'self.bulletnum', '+', '1'],
                    ['if', 'self.bulletnum', '==', 'self.bulletmax'],
                    ['set', 'self', 'bulletnum', '0'],
                    ['endif'],
                    ['endif'],
                    ['if', 'self.level', '==', '1'],
                    ['set',
                     'self',
                     'bulletname',
                     'self.name',
                     '+',
                     'bullet',
                     '+',
                     'self.bulletnum'],
                    ['create',
                     'spacebullet0',
                     'self.bulletname',
                     'self.x',
                     'self.y'],
                    ['set', 'self.bulletname', 'state', 'SHOT'],
                    ['set', 'self.bulletname', 'y_vel', 'self.shotspeed'],
                    ['set', 'self', 'bulletnum', 'self.bulletnum', '+', '1'],
                    ['if', 'self.bulletnum', '==', 'self.bulletmax'],
                    ['set', 'self', 'bulletnum', '0'],
                    ['endif'],
                    ['set',
                     'self',
                     'bulletname',
                     'self.name',
                     '+',
                     'bullet',
                     '+',
                     'self.bulletnum'],
                    ['create',
                     'spacebullet0',
                     'self.bulletname',
                     'self.w',
                     '/',
                     '3',
                     '+',
                     'self.x',
                     'self.y',
                     '+',
                     '16'],
                    ['set', 'self.bulletname', 'state', 'SHOT'],
                    ['set', 'self.bulletname', 'y_vel', 'self.shotspeed'],
                    ['set', 'self', 'bulletnum', 'self.bulletnum', '+', '1'],
                    ['if', 'self.bulletnum', '==', 'self.bulletmax'],
                    ['set', 'self', 'bulletnum', '0'],
                    ['endif'],
                    ['set',
                     'self',
                     'bulletname',
                     'self.name',
                     '+',
                     'bullet',
                     '+',
                     'self.bulletnum'],
                    ['create',
                     'spacebullet0',
                     'self.bulletname',
                     'self.w',
                     '/',
                     '3',
                     '*',
                     '2',
                     '+',
                     'self.x',
                     'self.y'],
                    ['set', 'self.bulletname', 'state', 'SHOT'],
                    ['set', 'self.bulletname', 'y_vel', 'self.shotspeed'],
                    ['set', 'self', 'bulletnum', 'self.bulletnum', '+', '1'],
                    ['if', 'self.bulletnum', '==', 'self.bulletmax'],
                    ['set', 'self', 'bulletnum', '0'],
                    ['endif'],
                    ['endif'],
                    ['if', 'self.level', '==', '2'],
                    ['set',
                     'self',
                     'bulletname',
                     'self.name',
                     '+',
                     'bullet',
                     '+',
                     'self.bulletnum'],
                    ['create',
                     'spacebullet0',
                     'self.bulletname',
                     'self.x',
                     '-',
                     '8',
                     'self.y'],
                    ['set', 'self.bulletname', 'state', 'SHOT'],
                    ['set', 'self.bulletname', 'y_vel', 'self.shotspeed'],
                    ['set', 'self', 'bulletnum', 'self.bulletnum', '+', '1'],
                    ['if', 'self.bulletnum', '==', 'self.bulletmax'],
                    ['set', 'self', 'bulletnum', '0'],
                    ['endif'],
                    ['set',
                     'self',
                     'bulletname',
                     'self.name',
                     '+',
                     'bullet',
                     '+',
                     'self.bulletnum'],
                    ['create',
                     'spacebullet0',
                     'self.bulletname',
                     'self.w',
                     '/',
                     '2',
                     '+',
                     'self.x',
                     '-',
                     '8',
                     'self.y',
                     '+',
                     '16'],
                    ['set', 'self.bulletname', 'state', 'SHOT'],
                    ['set', 'self.bulletname', 'y_vel', 'self.shotspeed'],
                    ['set', 'self', 'bulletnum', 'self.bulletnum', '+', '1'],
                    ['if', 'self.bulletnum', '==', 'self.bulletmax'],
                    ['set', 'self', 'bulletnum', '0'],
                    ['endif'],
                    ['set',
                     'self',
                     'bulletname',
                     'self.name',
                     '+',
                     'bullet',
                     '+',
                     'self.bulletnum'],
                    ['create',
                     'spacebullet0',
                     'self.name',
                     '+',
                     'bullet',
                     '+',
                     'self.bulletnum',
                     'self.w',
                     '+',
                     'self.x',
                     '-',
                     '8',
                     'self.y'],
                    ['set', 'self.bulletname', 'state', 'SHOT'],
                    ['set', 'self.bulletname', 'y_vel', 'self.shotspeed'],
                    ['set', 'self', 'bulletnum', 'self.bulletnum', '+', '1'],
                    ['if', 'self.bulletnum', '==', 'self.bulletmax'],
                    ['set', 'self', 'bulletnum', '0'],
                    ['endif'],
                    ['endif'],
                    ['if', 'self.level', '==', '3'],
                    ['set',
                     'self',
                     'bulletname',
                     'self.name',
                     '+',
                     'bullet',
                     '+',
                     'self.bulletnum'],
                    ['create',
                     'spacebullet0',
                     'self.bulletname',
                     'self.w',
                     '/',
                     '2',
                     '+',
                     'self.x',
                     '-',
                     '8',
                     'self.y',
                     '-',
                     '32'],
                    ['set', 'self.bulletname', 'state', 'BEAM'],
                    ['set', 'self.bulletname', 'y_vel', 'self.shotspeed'],
                    ['set', 'self', 'bulletnum', 'self.bulletnum', '+', '1'],
                    ['if', 'self.bulletnum', '==', 'self.bulletmax'],
                    ['set', 'self', 'bulletnum', '0'],
                    ['endif'],
                    ['endif']],
          'updateShot': [['if', 'inpA'],
                         ['set', 'self', 'calc', 'self.level', '==', '3'],
                         ['if',
                          'self.bulletcounter',
                          '>=',
                          'self.bulletfreq',
                          'or',
                          'self.calc'],
                         ['exec', 'shoot'],
                         ['set', 'self', 'bulletcounter', '0'],
                         ['endif'],
                         ['endif'],
                         ['set',
                          'self',
                          'bulletcounter',
                          'self.bulletcounter',
                          '+',
                          '1']],
          'updateSmoke': [['if', 'self.smokecounter', '==', 'self.smokefreq'],
                          ['set', 'self', 'smokecounter', '0'],
                          ['create',
                           'smokeball0',
                           'self.name',
                           '+',
                           'smokeball',
                           '+',
                           'self.smokenum',
                           'self.x',
                           '+',
                           'RAND?',
                           '+',
                           'RAND?',
                           '-',
                           'RAND?',
                           '-',
                           'RAND?',
                           'self.h',
                           '*',
                           '0.75',
                           '+',
                           'self.y'],
                          ['set',
                           'self',
                           'smokenum',
                           'self.smokenum',
                           '+',
                           '1'],
                          ['if', 'self.smokenum', '==', 'self.smokemax'],
                          ['set', 'self', 'smokenum', '0'],
                          ['endif'],
                          ['endif'],
                          ['set',
                           'self',
                           'smokecounter',
                           'self.smokecounter',
                           '+',
                           '1']]},
 'smokeball': {'BALL:0': [['set', 'self', 'y', 'self.y', '+', '1']],
               'BALL:45': [['goodbye']],
               'START:0': [['set', 'self', 'state', 'BALL'],
                           ['set', 'self', 'frame', '0'],
                           ['back']]},
 'smokeballrev': {'BALL:0': [['set', 'self', 'y', 'self.y', '-', '1']],
                  'BALL:45': [['goodbye']],
                  'START:0': [['set', 'self', 'state', 'BALL'],
                              ['set', 'self', 'frame', '0'],
                              ['back']]},
 'spacebullet': {'BALL:0': [['exec', 'updateCounter']],
                 'BEAM:0': [['back'], ['exec', 'updateCounter']],
                 'BEAM:1': [['exec', 'updateCounter']],
                 'BEAM:6': [['exec', 'updateCounter'],
                            ['set', 'self', 'frame', '1']],
                 'BYE:0': [['goodbye']],
                 'CROSS:0': [['exec', 'updateCounter']],
                 'CROSS:10': [['exec', 'updateCounter'],
                              ['set', 'self', 'frame', '0']],
                 'HIT': [['set', 'self', 'calc', 'self.name', '==', 'ship1'],
                         ['if', 'self.name', '==', 'ship0', 'or', 'self.calc'],
                         ['set', 'self', 'calc', 'related.state', '==', 'BEAM'],
                         ['if',
                          'related.state',
                          '==',
                          'SHOT',
                          'or',
                          'self.calc'],
                         ['break'],
                         ['endif'],
                         ['if', 'self.level', '==', '0'],
                         ['set', 'self', 'state', 'BROKE'],
                         ['set', 'self', 'frame', '0'],
                         ['set', 'self', 'x_vel', '0'],
                         ['set', 'self', 'y_vel', '0'],
                         ['endif'],
                         ['if', 'self.level', '!=', '0'],
                         ['set', 'ship0', 'level', '0'],
                         ['set', 'self', 'state', 'CRASH'],
                         ['set', 'self', 'frame', '0'],
                         ['set', 'self', 'x_vel', '0'],
                         ['set', 'self', 'y_vel', '0'],
                         ['endif'],
                         ['endif'],
                         ['if', 'self.name', '!=', 'ship0'],
                         ['set',
                          'self',
                          'calc1',
                          'related.state',
                          '==',
                          'BEAM'],
                         ['set',
                          'self',
                          'calc2',
                          'related.state',
                          '==',
                          'SHOT'],
                         ['if', 'not', 'self.calc1', 'nor', 'self.calc2'],
                         ['break'],
                         ['endif'],
                         ['if', 'self.hp'],
                         ['set', 'self', 'hp', 'self.hp', '-', '1'],
                         ['endif'],
                         ['if', 'self.hp', '==', '0'],
                         ['set',
                          'ship0',
                          'powerupcounter',
                          'ship0.powerupcounter',
                          '-',
                          '1'],
                         ['if', 'ship0.powerupcounter', '==', '0'],
                         ['create',
                          'powerup0',
                          'gamePowerUp',
                          'self.x',
                          'self.y'],
                         ['set',
                          'ship0',
                          'powerupcounter',
                          'ship0.powerupcountermax'],
                         ['endif'],
                         ['set', 'self', 'state', 'BROKE'],
                         ['set', 'self', 'frame', '0'],
                         ['set', 'self', 'x_vel', '0'],
                         ['set', 'self', 'y_vel', '0'],
                         ['endif'],
                         ['endif'],
                         ['set', 'self', 'hitname', 'self.name', '+', 'Hit!'],
                         ['create',
                          'fxhit0',
                          'self.hitname',
                          'related.x',
                          'related.y'],
                         ['set', 'related', 'state', 'BYE']],
                 'SHOT:0': [['exec', 'updateCounter']],
                 'SHOT:11': [['exec', 'updateCounter'],
                             ['set',
                              'self',
                              'direction',
                              'self.direction',
                              '*',
                              '-1'],
                             ['set', 'self', 'frame', '5']],
                 'SQUIG:0': [['exec', 'updateCounter']],
                 'SQUIG:10': [['exec', 'updateCounter'],
                              ['set',
                               'self',
                               'direction',
                               'self.direction',
                               '*',
                               '-1'],
                              ['set', 'self', 'frame', '0']],
                 'START:0': [['set', 'self', 'physics', '1'],
                             ['hitboxes', 'spacebullet'],
                             ['hurtboxes', 'spacebullet'],
                             ['set', 'self', 'counter', '200']],
                 'TINY:0': [['exec', 'updateCounter']],
                 'XCOLLISION': [['goodbye']],
                 'updateCounter': [['set',
                                    'self',
                                    'counter',
                                    'self.counter',
                                    '-',
                                    '1'],
                                   ['if', 'self.counter', '==', '0'],
                                   ['set', 'self', 'state', 'BYE'],
                                   ['endif']]},
 'titlecard': {'START:0': [['set', 'self', 'direction', '-1'],
                           ['set', 'self', 'state', 'PLAT']]},
 'triangleman': {'BROKE:0': [['exec', 'explode']],
                 'BROKE:60': [['goodbye']],
                 'BYE:0': [['goodbye']],
                 'SHIP:0': [['exec', 'updateShot']],
                 'SHIP:22': [['set', 'self', 'frame', '0'], ['exec', 'SHIP:0']],
                 'START:0': [['set', 'self', 'state', 'SHIP'],
                             ['set', 'self', 'bulletfreq', '30'],
                             ['set', 'self', 'bulletcounter', '28'],
                             ['set', 'self', 'bulletnum', '0'],
                             ['set', 'self', 'bulletmax', '8'],
                             ['set', 'self', 'shotspeed', '6'],
                             ['hitboxes', 'triangle'],
                             ['hurtboxes', 'triangle'],
                             ['set', 'self', 'explodenum', '0'],
                             ['set', 'self', 'explodemax', '8'],
                             ['set', 'self', 'explodecounter', '0'],
                             ['set', 'self', 'explodefreq', '8'],
                             ['set', 'self', 'hp', '4']],
                 'explode': [['if',
                              'self.explodecounter',
                              '==',
                              'self.explodefreq'],
                             ['set', 'self', 'explodecounter', '0'],
                             ['set', 'self', '_x', 'self.x'],
                             ['set', 'self', '_y', 'self.y'],
                             ['for', 'i', 'range', '3'],
                             ['set',
                              'self',
                              '_x',
                              'RAND?',
                              '*',
                              '-16',
                              '+',
                              'self._x'],
                             ['set',
                              'self',
                              '_x',
                              'RAND?',
                              '*',
                              '-3',
                              '+',
                              'self._x'],
                             ['set',
                              'self',
                              '_x',
                              'RAND?',
                              '*',
                              '16',
                              '+',
                              'self._x'],
                             ['set',
                              'self',
                              '_x',
                              'RAND?',
                              '*',
                              '3',
                              '+',
                              'self._x'],
                             ['set',
                              'self',
                              '_y',
                              'RAND?',
                              '*',
                              '-16',
                              '+',
                              'self._y'],
                             ['set',
                              'self',
                              '_y',
                              'RAND?',
                              '*',
                              '-3',
                              '+',
                              'self._y'],
                             ['set',
                              'self',
                              '_y',
                              'RAND?',
                              '*',
                              '16',
                              '+',
                              'self._y'],
                             ['set',
                              'self',
                              '_y',
                              'RAND?',
                              '*',
                              '-3',
                              '+',
                              'self._y'],
                             ['endfor'],
                             ['create',
                              'explode0',
                              'self.name',
                              '+',
                              'explode',
                              '+',
                              'self.explodenum',
                              'self._x',
                              'self._y'],
                             ['set',
                              'self',
                              'explodenum',
                              'self.explodenum',
                              '+',
                              '1'],
                             ['endif'],
                             ['set',
                              'self',
                              'explodecounter',
                              'self.explodecounter',
                              '+',
                              '1']],
                 'shoot': [['set',
                            'self',
                            'bulletname',
                            'self.name',
                            '+',
                            'bullet',
                            '+',
                            'self.bulletnum'],
                           ['create',
                            'spacebullet0',
                            'self.bulletname',
                            'self.w',
                            '/',
                            '2',
                            '+',
                            'self.x',
                            '-',
                            '8',
                            'self.y',
                            '+',
                            '48'],
                           ['set', 'self.bulletname', 'state', 'SQUIG'],
                           ['set',
                            'self.bulletname',
                            'y_vel',
                            'self.shotspeed'],
                           ['set',
                            'self',
                            'bulletnum',
                            'self.bulletnum',
                            '+',
                            '1'],
                           ['if', 'self.bulletnum', '==', 'self.bulletmax'],
                           ['set', 'self', 'bulletnum', '0'],
                           ['endif']],
                 'updateShot': [['if',
                                 'self.bulletcounter',
                                 '>=',
                                 'self.bulletfreq'],
                                ['exec', 'shoot'],
                                ['set', 'self', 'bulletcounter', '0'],
                                ['endif'],
                                ['set',
                                 'self',
                                 'bulletcounter',
                                 'self.bulletcounter',
                                 '+',
                                 '1']]},
 'trianglespawner': {'SPAWN:0': [['set', 'self', 'state', 'WAIT'],
                                 ['if', 'exists', 'self.spawnname'],
                                 ['break'],
                                 ['endif'],
                                 ['create',
                                  'triangleman0',
                                  'self.spawnname',
                                  'self.x',
                                  'self.y']],
                     'START:0': [['set', 'self', 'state', 'WAIT'],
                                 ['set',
                                  'self',
                                  'spawnname',
                                  'self.name',
                                  '+',
                                  'triangleman']]}}