SPRITESHEETS = {'background.png': {'space': ((0, 0), (256, 256))},
 'shmup.png': {'bballshot0': ((1536, 0), (48, 48)),
               'bballshot1': ((1536, 48), (48, 48)),
               'bballshot2': ((1824, 0), (48, 48)),
               'bballshot3': ((1824, 48), (48, 48)),
               'beam0': ((336, 64), (80, 32)),
               'beam1': ((336, 96), (80, 32)),
               'beedleship0': ((480, 0), (48, 48)),
               'beedleshipleft0': ((480, 48), (48, 48)),
               'beedleshipright0': ((528, 0), (48, 48)),
               'bossarmsdown': ((2224, 48), (80, 64)),
               'bossarmspin0': ((2880, 0), (112, 96)),
               'bossarmspin1': ((3024, 0), (112, 96)),
               'bossarmspin2': ((3168, 0), (112, 96)),
               'bossarmspin3': ((3312, 0), (112, 96)),
               'bossarmspin4': ((3456, 0), (112, 96)),
               'bossarmspin5': ((3600, 0), (112, 96)),
               'bossarmspin6': ((3744, 0), (112, 96)),
               'bossarmspray': ((3664, 96), (80, 32)),
               'bossarmsready': ((2512, 64), (80, 48)),
               'bossarmsswayleft': ((2368, 64), (80, 64)),
               'bossarmsswayright': ((2368, 0), (80, 64)),
               'bossarmsthrowleft0': ((2800, 0), (80, 48)),
               'bossarmsthrowleft1': ((2800, 48), (80, 48)),
               'bossarmsthrowright0': ((2656, 0), (80, 48)),
               'bossarmsthrowright1': ((2656, 48), (80, 48)),
               'bossarmsup': ((2512, 0), (80, 64)),
               'bossdress': ((2224, 0), (48, 48)),
               'bosshead0': ((2160, 0), (64, 112)),
               'bosshead1': ((2304, 0), (64, 112)),
               'bosshead2': ((2448, 0), (64, 112)),
               'bream0': ((336, 64), (80, 32)),
               'bulletball': ((416, 16), (16, 16)),
               'bulletflat': ((416, 64), (16, 32)),
               'bulletplus': ((416, 96), (16, 16)),
               'bulletsquig': ((416, 32), (16, 32)),
               'bulletx': ((416, 112), (16, 16)),
               'crow0': ((1744, 0), (64, 64)),
               'crow1': ((1872, 0), (112, 64)),
               'destroyer0': ((1584, 0), (128, 128)),
               'destroyer1': ((1728, 0), (112, 128)),
               'empty': ((272, 16), (16, 16)),
               'fireball0': ((240, 0), (32, 32)),
               'fireball1': ((272, 0), (16, 16)),
               'fxhit': ((112, 80), (16, 16)),
               'fxhit0': ((112, 80), (16, 16)),
               'fxhit1': ((128, 48), (16, 32)),
               'fxhit2': ((128, 80), (16, 32)),
               'fxhit3': ((128, 112), (16, 16)),
               'fxhit4': ((112, 96), (16, 32)),
               'fxhit5': ((96, 96), (16, 32)),
               'hpbarhuddisplay': ((1872, 64), (192, 64)),
               'playershot0': ((384, 0), (16, 32)),
               'playershot1': ((400, 0), (16, 32)),
               'playershot2': ((384, 32), (16, 32)),
               'playershot3': ((400, 32), (16, 32)),
               'powerup0': ((528, 80), (48, 48)),
               'powerup1': ((672, 80), (48, 48)),
               'powerup2': ((816, 80), (48, 48)),
               'powerup3': ((960, 80), (48, 48)),
               'quit_selected': ((576, 64), (64, 32)),
               'quit_unselected': ((592, 64), (48, 32)),
               'rockethealthbarpink': ((2048, 0), (32, 32)),
               'rockethealthbarred': ((2016, 0), (32, 32)),
               'rockethudplat00': ((1440, 0), (32, 32)),
               'rockethudplat01': ((1472, 0), (32, 32)),
               'rockethudplat02': ((1504, 0), (32, 32)),
               'rockethudplat10': ((1440, 32), (32, 32)),
               'rockethudplat11': ((1472, 32), (32, 32)),
               'rockethudplat12': ((1504, 32), (32, 32)),
               'rockethudplat20': ((1440, 64), (32, 32)),
               'rockethudplat21': ((1472, 64), (32, 32)),
               'rockethudplat22': ((1504, 64), (32, 32)),
               'rocketmenugerder': ((1104, 48), (16, 80)),
               'rocketmenuplat00': ((1008, 64), (32, 32)),
               'rocketmenuplat01': ((1040, 64), (32, 32)),
               'rocketmenuplat02': ((1072, 64), (32, 32)),
               'rocketmenuplat10': ((1008, 96), (32, 32)),
               'rocketmenuplat11': ((1040, 96), (32, 32)),
               'rocketmenuplat12': ((1072, 96), (32, 32)),
               'rocketmenuplat20': ((1008, 128), (32, 32)),
               'rocketmenuplat21': ((1040, 128), (32, 32)),
               'rocketmenuplat22': ((1072, 128), (32, 32)),
               'rocketmenustation': ((1008, 48), (96, 16)),
               'rockettitle': ((1152, 48), (256, 80)),
               'rockettriangle': ((1120, 96), (32, 32)),
               'shipbreak0': ((48, 64), (48, 64)),
               'shipleft0': ((48, 0), (48, 64)),
               'shipleft1': ((192, 0), (48, 64)),
               'shipleft2': ((336, 0), (48, 64)),
               'shipright0': ((0, 64), (48, 64)),
               'shipright1': ((144, 64), (48, 64)),
               'shipright2': ((288, 64), (48, 64)),
               'shipstraight0': ((0, 0), (48, 64)),
               'shipstraight1': ((144, 0), (48, 64)),
               'shipstraight2': ((288, 0), (48, 64)),
               'smokeball0': ((96, 0), (48, 48)),
               'smokeball1': ((96, 48), (32, 32)),
               'smokeball2': ((96, 80), (16, 16)),
               'start_selected': ((576, 96), (80, 16)),
               'start_unselected': ((592, 96), (64, 16)),
               'tinybullet': ((416, 0), (16, 16)),
               'triangleman0': ((432, 0), (48, 48)),
               'triangleman1': ((576, 0), (48, 48)),
               'triangleman2': ((720, 0), (48, 48)),
               'triangleman3': ((864, 0), (48, 48)),
               'triangleman4': ((1008, 0), (48, 48)),
               'triangleman5': ((1152, 0), (48, 48)),
               'warpin0': ((2736, 0), (48, 48)),
               'warpin1': ((2736, 48), (48, 48)),
               'warpin2': ((2592, 0), (48, 48)),
               'warpin3': ((2592, 48), (48, 48)),
               'warpinb0': ((3888, 0), (128, 128)),
               'warpinb1': ((4032, 0), (128, 128)),
               'warpinb2': ((4176, 0), (128, 128)),
               'warpinb3': ((4320, 0), (128, 128))}}
SPRITEMAPS = {'beedleship': {'BROKE:0': 'beedleship0',
                'BYE:0': 'empty',
                'FLY:0': 'beedleship0',
                'FLYLEFT:0': 'beedleshipleft0',
                'FLYRIGHT:0': 'beedleshipright0',
                'START:0': 'beedleship0'},
 'beedleshipspawner': {'SPAWN:0': 'warpin0',
                       'SPAWN:12': 'warpin3',
                       'SPAWN:15': 'empty',
                       'SPAWN:3': 'warpin1',
                       'SPAWN:6': 'warpin0',
                       'SPAWN:9': 'warpin2',
                       'START:0': 'empty',
                       'WAIT:0': 'empty'},
 'bgscroller': {'SCROLL:0': 'empty', 'START:0': 'empty'},
 'bgscrollerleft': {'START:0': 'empty'},
 'bossarms': {'BYE:0': 'empty',
              'DOWN:0': 'bossarmsdown',
              'PRAY:0': 'bossarmspray',
              'READY:0': 'bossarmsready',
              'SPIN:0': 'bossarmspin0',
              'SPIN:12': 'bossarmspin4',
              'SPIN:15': 'bossarmspin5',
              'SPIN:18': 'bossarmspin6',
              'SPIN:23': 'bossarmspray',
              'SPIN:3': 'bossarmspin1',
              'SPIN:6': 'bossarmspin2',
              'SPIN:9': 'bossarmspin3',
              'START:0': 'bossarmsdown',
              'SWAYLEFT:0': 'bossarmsswayleft',
              'SWAYRIGHT:0': 'bossarmsswayright',
              'THROWLEFT:0': 'bossarmsthrowleft0',
              'THROWLEFT:8': 'bossarmsthrowleft1',
              'THROWRIGHT:0': 'bossarmsthrowright0',
              'THROWRIGHT:8': 'bossarmsthrowright1',
              'UP:0': 'bossarmsup'},
 'bossbody': {'BYE:0': 'empty', 'DRESS:0': 'bossdress', 'START:0': 'bossdress'},
 'bosshead': {'BROKE:0': 'bosshead2',
              'BYE:0': 'empty',
              'HEAD0:0': 'bosshead0',
              'HEAD1:0': 'bosshead1',
              'HEAD2:0': 'bosshead2',
              'START:0': 'bosshead0'},
 'bosspawner': {'SPAWN:0': 'warpin0',
                'SPAWN:12': 'warpin3',
                'SPAWN:15': 'empty',
                'SPAWN:3': 'warpin1',
                'SPAWN:6': 'warpin0',
                'SPAWN:9': 'warpin2',
                'START:0': 'empty',
                'WAIT:0': 'empty'},
 'bowlershot': {'BBALL:0': 'bballshot0',
                'BBALL:3': 'bballshot1',
                'BBALL:5': 'bballshot2',
                'BBALL:6': 'bballshot3',
                'BYE:0': 'empty',
                'EXPLODE:0': 'empty',
                'START:0': 'bballshot0'},
 'bulletclear': {'START:0': 'empty'},
 'destroyer': {'BROKE:0': 'destroyer0',
               'BYE:0': 'empty',
               'FLY:0': 'destroyer0',
               'START:0': 'destroyer0'},
 'destroyerspawner': {'SPAWN:0': 'warpinb0',
                      'SPAWN:12': 'warpinb3',
                      'SPAWN:15': 'empty',
                      'SPAWN:3': 'warpinb1',
                      'SPAWN:6': 'warpinb0',
                      'SPAWN:9': 'warpinb2',
                      'START:0': 'empty',
                      'WAIT:0': 'empty'},
 'explode': {'BALL:0': 'fireball1',
             'BALL:15': 'fireball0',
             'BALL:30': 'fireball1',
             'START:0': 'fireball0'},
 'focuson': {'START:0': 'empty', 'WAIT:0': 'empty'},
 'fxhit': {'FX:0': 'fxhit0',
           'FX:1': 'fxhit1',
           'FX:2': 'fxhit2',
           'FX:3': 'fxhit3',
           'FX:4': 'fxhit4',
           'FX:5': 'fxhit5',
           'START:0': 'fxhit0'},
 'inviswall': {'START:0': 'empty', 'WALL:0': 'empty'},
 'platformrockethudL': {'PLATFORM00': 'rockethudplat00',
                        'PLATFORM01': 'rockethudplat01',
                        'PLATFORM02': 'rockethudplat02',
                        'PLATFORM10': 'rockethudplat10',
                        'PLATFORM11': 'rockethudplat11',
                        'PLATFORM12': 'rockethudplat12',
                        'PLATFORM20': 'rockethudplat20',
                        'PLATFORM21': 'rockethudplat21',
                        'PLATFORM22': 'rockethudplat22'},
 'platformrockethudR': {'PLATFORM00': 'rockethudplat00',
                        'PLATFORM01': 'rockethudplat01',
                        'PLATFORM02': 'rockethudplat02',
                        'PLATFORM10': 'rockethudplat10',
                        'PLATFORM11': 'rockethudplat11',
                        'PLATFORM12': 'rockethudplat12',
                        'PLATFORM20': 'rockethudplat20',
                        'PLATFORM21': 'rockethudplat21',
                        'PLATFORM22': 'rockethudplat22'},
 'platformrocketmenu': {'PLATFORM00': 'rocketmenuplat00',
                        'PLATFORM01': 'rocketmenuplat01',
                        'PLATFORM02': 'rocketmenuplat02',
                        'PLATFORM10': 'rocketmenuplat10',
                        'PLATFORM11': 'rocketmenuplat11',
                        'PLATFORM12': 'rocketmenuplat12',
                        'PLATFORM20': 'rocketmenuplat20',
                        'PLATFORM21': 'rocketmenuplat21',
                        'PLATFORM22': 'rocketmenuplat22'},
 'powerup': {'BYE:0': 'empty',
             'POWERUP:0': 'powerup0',
             'POWERUP:1': 'powerup1',
             'POWERUP:3': 'powerup2',
             'POWERUP:5': 'powerup3',
             'START:0': 'powerup0'},
 'rocketcrow': {'BROKE:0': 'crow0',
                'BYE:0': 'empty',
                'CROW:0': 'crow0',
                'CROW:15': 'crow1',
                'START:0': 'crow0'},
 'rocketcrowspawner': {'SPAWN:0': 'warpin0',
                       'SPAWN:12': 'warpin3',
                       'SPAWN:15': 'empty',
                       'SPAWN:3': 'warpin1',
                       'SPAWN:6': 'warpin0',
                       'SPAWN:9': 'warpin2',
                       'START:0': 'empty',
                       'WAIT:0': 'empty'},
 'rocketgamemanager': {'PLAY0:0': 'empty',
                       'PLAY1:0': 'empty',
                       'PLAY2:0': 'empty',
                       'PLAY3:0': 'empty',
                       'PLAY4:0': 'empty',
                       'PLAY5:0': 'empty',
                       'START:0': 'empty'},
 'rockethpbarsegment': {'LOW:0': 'rockethealthbarpink',
                        'OFF:0': 'empty',
                        'ON:0': 'rockethealthbarred',
                        'START:0': 'empty'},
 'rockethpdisplay': {'OFF:0': 'empty',
                     'ON:0': 'hpbarhuddisplay',
                     'START:0': 'empty'},
 'rockethpmanager': {'END:0': 'empty',
                     'OFF:0': 'empty',
                     'ON:0': 'empty',
                     'START:0': 'empty'},
 'rocketmenugerder': {'PLAT:0': 'rocketmenugerder',
                      'START:0': 'rocketmenugerder'},
 'rocketmenustation': {'PLAT:0': 'rocketmenustation',
                       'START:0': 'rocketmenustation'},
 'rocketmenutriangle': {'PLAT:0': 'rockettriangle',
                        'START:0': 'rockettriangle'},
 'rocketquitbutton': {'BTN:0': 'quit_unselected', 'START:0': 'quit_unselected'},
 'rocketspawnmanager': {'PLAY:0': 'empty', 'START:0': 'empty'},
 'rocketstartbutton': {'BTN:0': 'start_unselected',
                       'START:0': 'start_unselected'},
 'ship': {'BROKE:0': 'shipbreak0',
          'CRASH:0': 'shipbreak0',
          'CRASH:10': 'empty',
          'CRASH:12': 'shipbreak0',
          'CRASH:20': 'empty',
          'CRASH:22': 'shipbreak0',
          'CRASH:30': 'empty',
          'FLY:0': 'shipstraight0',
          'FLY:3': 'shipstraight1',
          'FLY:6': 'shipstraight2',
          'FLYLEFT:0': 'shipleft0',
          'FLYLEFT:3': 'shipleft1',
          'FLYLEFT:6': 'shipleft2',
          'FLYRIGHT:0': 'shipright0',
          'FLYRIGHT:3': 'shipright1',
          'FLYRIGHT:6': 'shipright2',
          'START:0': 'shipstraight0',
          'WAIT:0': 'shipstraight0'},
 'smokeball': {'BALL:0': 'smokeball0',
               'BALL:15': 'smokeball1',
               'BALL:30': 'smokeball2',
               'START:0': 'smokeball0'},
 'smokeballrev': {'BALL:0': 'smokeball0',
                  'BALL:15': 'smokeball1',
                  'BALL:30': 'smokeball2',
                  'START:0': 'smokeball0'},
 'spacebullet': {'BALL:0': 'bulletball',
                 'BEAM:0': 'beam0',
                 'BEAM:3': 'beam1',
                 'BYE:0': 'empty',
                 'CROSS:0': 'bulletplus',
                 'CROSS:5': 'bulletx',
                 'FOLLOW:0': 'bulletball',
                 'SHOT:0': 'playershot0',
                 'SHOT:3': 'playershot1',
                 'SHOT:5': 'playershot2',
                 'SHOT:8': 'playershot3',
                 'SQUIG:0': 'bulletflat',
                 'SQUIG:5': 'bulletsquig',
                 'START:0': 'empty',
                 'TINY:0': 'tinybullet'},
 'titlecard': {'PLAT:0': 'rockettitle', 'START:0': 'rockettitle'},
 'triangleman': {'BROKE:0': 'triangleman0',
                 'BYE:0': 'empty',
                 'SHIP:0': 'triangleman0',
                 'SHIP:11': 'triangleman2',
                 'SHIP:14': 'triangleman3',
                 'SHIP:17': 'triangleman4',
                 'SHIP:20': 'triangleman5',
                 'SHIP:8': 'triangleman1',
                 'START:0': 'triangleman0'},
 'trianglespawner': {'SPAWN:0': 'warpin0',
                     'SPAWN:12': 'warpin3',
                     'SPAWN:15': 'empty',
                     'SPAWN:3': 'warpin1',
                     'SPAWN:6': 'warpin0',
                     'SPAWN:9': 'warpin2',
                     'START:0': 'empty',
                     'WAIT:0': 'empty'}}
OFFSETS = {'beedleship': {'beedleship0': [0, 0],
                'beedleshipleft0': [0, 0],
                'beedleshipright0': [0, 0],
                'empty': [0, 0]},
 'beedleshipspawner': {'empty': [0, 0],
                       'warpin0': [0, 0],
                       'warpin1': [0, 0],
                       'warpin2': [0, 0],
                       'warpin3': [0, 0]},
 'bgscroller': {'empty': [0, 0]},
 'bgscrollerleft': {'empty': [0, 0]},
 'bossarms': {'bossarmsdown': [-16, 0],
              'bossarmspin0': [-32, -32],
              'bossarmspin1': [-32, -32],
              'bossarmspin2': [-32, -32],
              'bossarmspin3': [-32, -32],
              'bossarmspin4': [-32, -32],
              'bossarmspin5': [-32, -32],
              'bossarmspin6': [-32, -32],
              'bossarmspray': [-16, 0],
              'bossarmsready': [-16, 0],
              'bossarmsswayleft': [-16, 0],
              'bossarmsswayright': [-16, 0],
              'bossarmsthrowleft0': [-8, -28],
              'bossarmsthrowleft1': [-8, 0],
              'bossarmsthrowright0': [-24, -28],
              'bossarmsthrowright1': [-24, 0],
              'bossarmsup': [-16, -32],
              'empty': [0, 0]},
 'bossbody': {'bossdress': [0, 0], 'empty': [0, 0]},
 'bosshead': {'bosshead0': [0, 0],
              'bosshead1': [0, 0],
              'bosshead2': [0, 0],
              'empty': [0, 0]},
 'bosspawner': {'empty': [0, 0],
                'warpin0': [0, 0],
                'warpin1': [0, 0],
                'warpin2': [0, 0],
                'warpin3': [0, 0]},
 'bowlershot': {'bballshot0': [0, 0],
                'bballshot1': [0, 0],
                'bballshot2': [0, 0],
                'bballshot3': [0, 0],
                'empty': [0, 0]},
 'bulletclear': {'empty': [0, 0]},
 'destroyer': {'destroyer0': [0, 0], 'empty': [0, 0]},
 'destroyerspawner': {'empty': [0, 0],
                      'warpinb0': [0, 0],
                      'warpinb1': [0, 0],
                      'warpinb2': [0, 0],
                      'warpinb3': [0, 0]},
 'explode': {'fireball0': [8, 8], 'fireball1': [16, 16]},
 'focuson': {'empty': [0, 0]},
 'fxhit': {'fxhit0': [0, 0],
           'fxhit1': [0, 0],
           'fxhit2': [0, 0],
           'fxhit3': [0, 0],
           'fxhit4': [0, 0],
           'fxhit5': [0, 0]},
 'inviswall': {'empty': [0, 0]},
 'platformrockethudL': {'rockethudplat00': [0, 0],
                        'rockethudplat01': [0, 0],
                        'rockethudplat02': [0, 0],
                        'rockethudplat10': [0, 0],
                        'rockethudplat11': [0, 0],
                        'rockethudplat12': [0, 0],
                        'rockethudplat20': [0, 0],
                        'rockethudplat21': [0, 0],
                        'rockethudplat22': [0, 0]},
 'platformrockethudR': {'rockethudplat00': [0, 0],
                        'rockethudplat01': [0, 0],
                        'rockethudplat02': [0, 0],
                        'rockethudplat10': [0, 0],
                        'rockethudplat11': [0, 0],
                        'rockethudplat12': [0, 0],
                        'rockethudplat20': [0, 0],
                        'rockethudplat21': [0, 0],
                        'rockethudplat22': [0, 0]},
 'platformrocketmenu': {'rocketmenuplat00': [0, 0],
                        'rocketmenuplat01': [0, 0],
                        'rocketmenuplat02': [0, 0],
                        'rocketmenuplat10': [0, 0],
                        'rocketmenuplat11': [0, 0],
                        'rocketmenuplat12': [0, 0],
                        'rocketmenuplat20': [0, 0],
                        'rocketmenuplat21': [0, 0],
                        'rocketmenuplat22': [0, 0]},
 'powerup': {'empty': [0, 0],
             'powerup0': [0, 0],
             'powerup1': [0, 0],
             'powerup2': [0, 0],
             'powerup3': [0, 0]},
 'rocketcrow': {'crow0': [0, 0], 'crow1': [-16, 0], 'empty': [0, 0]},
 'rocketcrowspawner': {'empty': [0, 0],
                       'warpin0': [0, 0],
                       'warpin1': [0, 0],
                       'warpin2': [0, 0],
                       'warpin3': [0, 0]},
 'rocketgamemanager': {'empty': [0, 0]},
 'rockethpbarsegment': {'empty': [0, 0],
                        'rockethealthbarpink': [0, 0],
                        'rockethealthbarred': [0, 0]},
 'rockethpdisplay': {'empty': [0, 0], 'hpbarhuddisplay': [0, 0]},
 'rockethpmanager': {'empty': [0, 0]},
 'rocketmenugerder': {'rocketmenugerder': [0, 0]},
 'rocketmenustation': {'rocketmenustation': [0, 0]},
 'rocketmenutriangle': {'rockettriangle': [0, 0]},
 'rocketquitbutton': {'quit_unselected': [0, 0]},
 'rocketspawnmanager': {'empty': [0, 0]},
 'rocketstartbutton': {'start_unselected': [0, 0]},
 'ship': {'empty': [0, 0],
          'shipbreak0': [0, 0],
          'shipleft0': [0, 0],
          'shipleft1': [0, 0],
          'shipleft2': [0, 0],
          'shipright0': [0, 0],
          'shipright1': [0, 0],
          'shipright2': [0, 0],
          'shipstraight0': [0, 0],
          'shipstraight1': [0, 0],
          'shipstraight2': [0, 0]},
 'smokeball': {'smokeball0': [0, 0],
               'smokeball1': [8, 8],
               'smokeball2': [16, 16]},
 'smokeballrev': {'smokeball0': [0, 0],
                  'smokeball1': [8, 8],
                  'smokeball2': [16, 16]},
 'spacebullet': {'beam0': [-32, 0],
                 'beam1': [-32, 0],
                 'bulletball': [0, 0],
                 'bulletflat': [0, 0],
                 'bulletplus': [0, 0],
                 'bulletsquig': [0, 0],
                 'bulletx': [0, 0],
                 'empty': [0, 0],
                 'playershot0': [0, 0],
                 'playershot1': [0, 0],
                 'playershot2': [0, 0],
                 'playershot3': [0, 0],
                 'tinybullet': [0, 0]},
 'titlecard': {'rockettitle': [0, 0]},
 'triangleman': {'empty': [0, 0],
                 'triangleman0': [0, 0],
                 'triangleman1': [0, 0],
                 'triangleman2': [0, 0],
                 'triangleman3': [0, 0],
                 'triangleman4': [0, 0],
                 'triangleman5': [0, 0]},
 'trianglespawner': {'empty': [0, 0],
                     'warpin0': [0, 0],
                     'warpin1': [0, 0],
                     'warpin2': [0, 0],
                     'warpin3': [0, 0]}}