WORLDS = {'root': {'actors': ['smokeball0',
                     'ship0',
                     'bgscroller0',
                     'spacebullet0',
                     'powerup0',
                     'powerup2',
                     'powerup3',
                     'triangleman0',
                     'triangleman1',
                     'triangleman2',
                     'triangleman3',
                     'triangleman4',
                     'triangleman5',
                     'triangleman6',
                     'triangleman7',
                     'explode0',
                     'fxhit0'],
          'background': 'space',
          'name': 'root',
          'x_lock': None,
          'y_lock': None}}