WORLDS = {'loadingzone': {'actors': ['explode0',
                            'smokeball0',
                            'powerup0',
                            'fxhit0',
                            'spacebullet0',
                            'triangleman0',
                            'smokeballrev0',
                            'beedleship0',
                            'bowlershot0',
                            'destroyer0',
                            'bosshead0',
                            'bossbody0',
                            'bossarms0'],
                 'background': 'space',
                 'name': 'loadingzone',
                 'x_lock': None,
                 'y_lock': None},
 'root': {'actors': ['platformrocketmenu0',
                     'rocketmenustation0',
                     'rocketmenugerder0',
                     'bgscrollerleft0',
                     'ship1',
                     'rocketmenutriangle0',
                     'titlecard0',
                     'inviswall4',
                     'inviswall5',
                     'inviswall6',
                     'rocketquitbutton0',
                     'rocketstartbutton0',
                     'focuson1'],
          'background': 'space',
          'name': 'root',
          'x_lock': None,
          'y_lock': None},
 'spacelevel': {'actors': ['inviswall2',
                           'inviswall3',
                           'ship0',
                           'focuson0',
                           'platformrockethudR0',
                           'platformrockethudL0',
                           'rocketgamemanager0',
                           'trianglespawner0',
                           'trianglespawner1',
                           'trianglespawner2',
                           'trianglespawner3',
                           'trianglespawner4',
                           'trianglespawner5',
                           'trianglespawner6',
                           'trianglespawner7',
                           'trianglespawner8',
                           'trianglespawner9',
                           'bulletclear0',
                           'bulletclear1',
                           'rocketspawnmanager0',
                           'bgscroller0',
                           'inviswall0',
                           'inviswall1',
                           'beedleshipspawner0',
                           'beedleshipspawner1',
                           'beedleshipspawner2',
                           'beedleshipspawner3',
                           'beedleshipspawner4',
                           'beedleshipspawner5',
                           'beedleshipspawner6',
                           'beedleshipspawner7',
                           'beedleshipspawner8',
                           'beedleshipspawner9',
                           'destroyerspawner0',
                           'destroyerspawner1',
                           'destroyerspawner2',
                           'destroyerspawner3',
                           'bosspawner0'],
                'background': 'space',
                'name': 'spacelevel',
                'x_lock': None,
                'y_lock': None}}