WORLDS = {'endscene': {'actors': ['endflavortext0',
                         'youwin0',
                         'alienplanet1',
                         'ship2',
                         'inviswall0',
                         'inviswall1',
                         'inviswall2',
                         'bulletclear0',
                         'focuson2',
                         'endscenemanager0',
                         'alienplanet0'],
              'background': 'space',
              'name': 'endscene',
              'x_lock': None,
              'y_lock': None},
 'loadingzone': {'actors': ['explode0',
                            'smokeball0',
                            'powerup0',
                            'fxhit0',
                            'spacebullet0',
                            'triangleman0',
                            'smokeballrev0',
                            'beedleship0',
                            'bowlershot0',
                            'destroyer0',
                            'bosshead0',
                            'bossbody0',
                            'bossarms0',
                            'rocketcrow0'],
                 'background': 'space',
                 'name': 'loadingzone',
                 'x_lock': None,
                 'y_lock': None},
 'root': {'actors': ['platformrocketmenu0',
                     'rocketmenustation0',
                     'rocketmenugerder0',
                     'bgscrollerleft0',
                     'ship1',
                     'rocketmenutriangle0',
                     'titlecard0',
                     'inviswall4',
                     'inviswall5',
                     'inviswall6',
                     'rocketquitbutton0',
                     'rocketstartbutton0',
                     'focuson1'],
          'background': 'space',
          'name': 'root',
          'x_lock': None,
          'y_lock': None},
 'spacelevel': {'actors': ['ship0',
                           'focuson0',
                           'platformrockethudR0',
                           'platformrockethudL0',
                           'rocketgamemanager0',
                           'trianglespawner0',
                           'trianglespawner1',
                           'trianglespawner2',
                           'trianglespawner3',
                           'trianglespawner4',
                           'trianglespawner5',
                           'trianglespawner6',
                           'trianglespawner7',
                           'trianglespawner8',
                           'trianglespawner9',
                           'rocketspawnmanager0',
                           'bgscroller0',
                           'beedleshipspawner0',
                           'beedleshipspawner1',
                           'beedleshipspawner2',
                           'beedleshipspawner3',
                           'beedleshipspawner4',
                           'beedleshipspawner5',
                           'beedleshipspawner6',
                           'beedleshipspawner7',
                           'beedleshipspawner8',
                           'beedleshipspawner9',
                           'destroyerspawner0',
                           'destroyerspawner1',
                           'destroyerspawner2',
                           'destroyerspawner3',
                           'bosspawner0',
                           'rocketcrowspawner0',
                           'rocketcrowspawner1',
                           'rockethpmanager0',
                           'platformrocketmenu1',
                           'platformrocketmenu2',
                           'rockethpbarsegment0',
                           'rockethpbarsegment1',
                           'rockethpbarsegment2',
                           'rockethpbarsegment3',
                           'rockethpbarsegment4',
                           'rockethpbarsegment5',
                           'rockethpbarsegment6',
                           'rockethpbarsegment7',
                           'rockethpbarsegment8',
                           'rockethpbarsegment9',
                           'rockethpbarsegment10',
                           'rockethpbarsegment11',
                           'rockethpdisplay0',
                           'rockethudblinker0',
                           'rockethudblinker1',
                           'rockethudblinker2',
                           'rockethudblinker3',
                           'cautionsign0',
                           'spaceport0',
                           'thermometerpiece0',
                           'thermometerpiece1',
                           'thermometerpiece2',
                           'thermometerpiece3',
                           'thermometerpiece4',
                           'thermometerpiece5',
                           'thermometerpiece6',
                           'thermometerpiece7',
                           'thermometerpiece8',
                           'thermometerpiece9',
                           'thermometerpiece10',
                           'thermometerpiece11',
                           'thermometerend0',
                           'thermometerbottom0'],
                'background': 'space',
                'name': 'spacelevel',
                'x_lock': None,
                'y_lock': None}}